---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    enableNodeFeatureApi: true
    featureGates:
      NodeFeatureAPI: true
    worker:
      config:
        core:
          sources:
            pci:
              deviceClassWhitelist:
                - "02"
                - "0200"
                - "0207"
                - "0300"
                - "0302"
              deviceLabelFields:
                - vendor
            usb:
              deviceClassWhitelist:
                - "0e"
                - "ef"
                - "fe"
                - "ff"
              deviceLabelFields:
                - "class"
                - "vendor"
                - "device"
            custom:
    master:
        config:
          extraLabelNs: ["nvidia.com"]
    prometheus:
      enable: true
