---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-webhook
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor-container-webhook
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: harbor-webhook
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    port: 9443
    certDir: "./hack/certs"
    healthAddr: ":8080"
    metricsAddr: ":8081"
    rules:
      - name: 'docker.io rewrite rule'
        matches:
          - '^docker.io'
        excludes:
          - '.*goharbor.*'
        replace: 'harbor.skynerv.com/local-docker'
        checkUpstream: true
        authSecretName: harbor-image-pull-secret
      - name: 'hub.docker.com rewrite rule'
        matches:
          - '^hub.docker.com'
        excludes:
          - '.*goharbor.*'
        replace: 'harbor.skynerv.com/local-docker'
        checkUpstream: true
        authSecretName: harbor-image-pull-secret
      - name: 'ghcr.io rewrite rule'
        matches:
          - '^ghcr.io'
        excludes:
          - '.*goharbor.*'
        replace: 'harbor.skynerv.com/local-github'
        checkUpstream: true
        authSecretName: harbor-image-pull-secret
      - name: 'quay.io rewrite rule'
        matches:
          - '^quay.io'
        excludes:
          - '.*goharbor.*'
        replace: 'harbor.skynerv.com/local-quay'
        checkUpstream: true
        authSecretName: harbor-image-pull-secret
      - name: 'gcr.io rewrite rule'
        matches:
          - '^gcr.io'
        excludes:
          - '.*goharbor.*'
        replace: 'harbor.skynerv.com/local-gcr'
        checkUpstream: true
        authSecretName: harbor-image-pull-secret
      - name: 'k8s.gcr.io rewrite rule'
        matches:
          - '^k8s.gcr.io'
        excludes:
          - '.*goharbor.*'
        replace: 'harbor.skynerv.com/local-gcr-k8s'
        checkUpstream: true
        authSecretName: harbor-image-pull-secret