---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 19.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    architecture: standalone
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Disable RDB persistence, AOF persistence already enabled.
      databases 80
    auth:
      enabled: false
      sentinel: false
    master:
      resources:
        requests:
          cpu: 10m
          memory: 1Gi
        limits:
          memory: 3Gi
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    sentinel:
      enabled: false
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
    networkPolicy:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
