---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  values:
    replicas: 1
    hostname: rancher.${SECRET_DOMAIN}
    tls: ingress
    ingress:
      enabled: true
      includeDefaultExtraAnnotations: true
      ingressClassName: internal
      tls:
        source: secret
        secretName: rancher-tls
    bootstrapPassword: "${SECRET_RANCHER_ADMIN_PASSWORD}"
    noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local