---
apiVersion: v1
kind: Secret
metadata:
  name: vm-additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |

    - job_name: vnstat
      scrape_interval: 1m
      scrape_timeout: 10s
      static_configs:
        - targets:
            - "vnstat.observability.${INTERNAL_SERVICE_DOMAIN}:8685"

    - job_name: smtp-relay
      scrape_interval: 1m
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - "smtp-relay.service.${INTERNAL_SERVICE_DOMAIN}:9749"

    - job_name: smartctl-exporter
      scrape_interval: 10m
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - "smartctl-exporter.observability.${INTERNAL_SERVICE_DOMAIN}:80"
            # - "gateway.${INTERNAL_SERVICE_DOMAIN}:9633"