---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./alertmanagerconfig.yaml
  - ./k3s-metrics-service.yaml
  - ./k3s-metrics-service-monitor.yaml