---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./extrascrapes.yaml
  - ./alertmanagerconfig.yaml
  - ./vmpodscrape.yaml
  - ./servicescrape.yaml