---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service
resources:
  - ./pvc
  - ./externalsecret.yaml
  - ./helmrelease.yaml

patchesStrategicMerge:
  - ./patches/postgres.yaml