---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./flaresolverr/ks.yaml
  - ./media-storage/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./sftpgo/ks.yaml
  - ./jellyfin/ks.yaml
  - ./recyclarr/ks.yaml
  - ./mainteinerr/ks.yaml
  - ./jellyseerr/ks.yaml