---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 60m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 60m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 10007

        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-02-06T21-36-22Z

            env:
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}
              MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_URL: https://prometheus.${SECRET_DOMAIN}
              MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
              MINIO_UPDATE: "off"

            envFrom:
              - secretRef:
                  name: minio-secret

            args: ["server", "/data", "--console-address", ":9001"]

            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 2048Mi

    service:
      main:
        enabled: true
        ports:
          http:
            port: 9001
          api:
            enabled: true
            port: 9000

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &console-host minio.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *console-host
      s3:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
          nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
        hosts:
          - host: &api-host s3.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: api
        tls:
          - hosts:
              - *api-host

    persistence:
      config:
        enabled: true
        existingClaim: minio-storage
        globalMounts:
          - path: /data