apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: storage
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:65kYhhXsgVQGkq6aZtqUap+2,iv:s60Ysuu/xGJChUVT5RXveiF/1eTQupw0cfFxy1qooaM=,tag:SUWEHQPgNvmZqfn0QqZ1gw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:uzvoyGuus1Cjk8qTMdEY7zWscZlTFA==,iv:OUfC1pinHh4p3kfXeyjzMZaACPvxpOsrHS/SnoHwcw4=,tag:Hjw0yjdWMA3tn5CCbkdrRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RkZSL0YwUGpTV0xJUm9m
            Q2E4TkJJakRyUUplYzlmTWJMRys2ekJwSUJ3CnE0R2xyK2RncVhOYnRHa0FOc24v
            Zkt4dGRTVThXV3d4MmVWM2MzUjhKK2sKLS0tIHhiOUoxbXdrK0hrNGkvQWdZTVR1
            dE5mK2dBUXNEb3ExUlhVRkJta1F1TEEK9vxUNpUPSuuhSZPKT9elivyAqLKS8KqA
            +oDrwYwTKZGxJd3OLKGzftWdz68Lf+bJMBEFoVFwxkhoHl4oW/sw4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T10:00:54Z"
    mac: ENC[AES256_GCM,data:58YwVphn17hbmpZqOnGpFVKC68jhDWV4Fn0+ewAIVp5AEJ1ZQwElXMAlR2/uAEY3cfjL5LDpJ1SqVsNLj4MAcsfav0V1DXHsMqogxtWp/gy8eIEW2z/LqzJbVnwqtr0YGu9yE+wN1yy/dBps/dUekihm2vdT2stNBpw6djXfvkU=,iv:vzyc8flxP5Y6UfNKwRqTaxAB/l7NBXSL6dqn4Tw81v4=,tag:9JU2Y5w2IsE5d09IfKiraA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
