# yaml-language-server: $schema=https://frigate.skynerv.com/api/config/schema.json
mqtt:
  enabled: True
  host: mosquitto.home.svc.cluster.local
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 30

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /data/frigate.db

tls:
  enabled: False

audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8

logger:
  default: warning
  logs:
    frigate.event: debug

auth:
  enabled: false

birdseye:
  enabled: True
  restream: False
  width: 2304
  height: 1296
  quality: 1
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-nvidia-h264
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy

detect:
  width: 640
  height: 360
  fps: 10
  enabled: True

objects:
  track:
    - person
    - dog
    - car
    - bus
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

record:
  enabled: True
  expire_interval: 60
  sync_recordings: True
  retain:
    days: 30
    mode: all
  export:
    timelapse_args: "-vf setpts=0.04*PTS -r 30"
  preview:
    quality: very_high
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: False
  crop: False
  required_zones: []
  retain:
    default: 30
    objects:
      person: 30
      car: 30
  quality: 90

go2rtc:
  streams:
    gates_hq:
      - rtsp://admin:12332145@192.168.108.104:554/stream1
      - "ffmpeg:gates_hq#audio=aac"
    gates_lq:
      - rtsp://admin:12332145@192.168.108.104:554/stream2
      - "ffmpeg:gates_lq#audio=aac"
    door_hq:
      - ffmpeg:rtsp://user:12332145@192.168.108.101:554/ch0_0#video=h264#hardware#audio=aac
    door_lq:
      - ffmpeg:rtsp://user:12332145@192.168.108.101:554/ch0_1#video=h264#hardware#audio=aac
    dvor_gates_hq:
      - rtsp://admin:12332145@192.168.108.210:554/stream1
      - "ffmpeg:dvor_gates_hq#audio=aac"
    dvor_gates_lq:
      - rtsp://admin:12332145@192.168.108.210:554/stream2
      - "ffmpeg:dvor_gates_lq#audio=aac"
    dom2_hq:
      - ffmpeg:rtsp://user:12332145@192.168.108.190:554/ch0_0#video=h264#hardware=cuda#audio=aac
    dom2_lq:
      - ffmpeg:rtsp://user:12332145@192.168.108.190:554/ch0_1#video=h264#hardware=cuda#audio=aac
    street_hq:
      - rtsp://admin:12332145@192.168.108.175:8554/Streaming/Channels/101
      - "ffmpeg:street_hq#video=copy#audio=aac"
    street_lq:
      - rtsp://admin:12332145@192.168.108.175:8554/Streaming/Channels/102
      - "ffmpeg:street_lq#video=copy#audio=aac"
  webrtc:
    candidates:
      - 192.168.108.55:8555
      - stun:8555

cameras:
  gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/gates_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 848
      height: 480
      fps: 8
      enabled: True
    live:
      stream_name: gates_hq
      quality: 1
    webui_url: ""
    zones:
      inside_gates:
        coordinates: 797,423,802,368,735,307,674,265,630,332
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
          - car
      entryway:
        coordinates: 484,82,391,41,118,218,164,332
        inertia: 5
        loitering_time: 5
        objects:
          - car
          - bus
      guests:
        coordinates: 596,249,513,221,365,370,436,453
        inertia: 5
        loitering_time: 4
        objects:
          - person
    motion:
      mask:
        - 0,33,61,0,144,0,622,0,493,81,409,33,118,233,161,334,0,480
        - 413,480,425,457,319,383,510,199,603,183,631,113,654,72,708,76,752,0,621,0,492,85,0,455,0,480
    review:
      alerts:
        labels:
          - car
          - person
          - bus
        required_zones:
          - entryway
          - guests
          - inside_gates
      detections:
        labels:
          - car
          - person
          - bus
        required_zones:
          - entryway
          - guests
          - inside_gates
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 500
      quality: 100
    birdseye:
      order: 0
  door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/door_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/door_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: door_hq
      quality: 1
    webui_url: "https://192.168.108.104/"
    motion:
      mask: []
    zones:
      near_the_door:
        coordinates: 159,360,515,360,517,326,210,317
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
          - car
      dvor:
        coordinates: 513,151,389,147,327,212,269,267,484,298
        inertia: 5
        objects:
          - car
          - person
      tropinka:
        coordinates: 576,203,591,47,553,51,539,197
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - dog
      parkovka:
        coordinates: 516,171,516,94,395,80,363,138
        inertia: 5
        objects:
          - person
          - dog
      sad:
        coordinates: 337,193,326,0,68,67,0,89,0,360,125,360
        inertia: 5
        objects:
          - person
          - dog
          - cat
    objects:
      filters:
        dog:
          mask:
            - 470,360,502,257,515,156,384,136,333,207,162,360
    review:
      alerts:
        labels:
          - person
      detections:
        labels:
          - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 1
  dvor_gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dvor_gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/dvor_gates_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 848
      height: 480
      fps: 8
      enabled: True
    live:
      stream_name: dvor_gates_hq
      quality: 1
    webui_url: "https://192.168.108.210/"
    motion:
      mask: []
    zones:
      before_gates:
        coordinates: 320,198,522,186,498,21,382,21,353,30,358,77
        inertia: 5
        loitering_time: 3
        objects:
          - person
          - car
      at_the_door:
        coordinates: 158,314,261,320,296,177,215,184
        inertia: 5
        loitering_time: 3
        objects:
          - person
      in_the_garden:
        coordinates: 848,480,848,74,714,21,583,0,508,41,612,480
        inertia: 5
        loitering_time: 2
        objects:
          - person
      driveway:
        coordinates: 201,480,592,480,520,198,302,204
        inertia: 5
        loitering_time: 2
        objects:
          - person
          - car
    objects:
      filters:
        dog:
          mask:
            - 440,360,372,0,284,0,161,360
    review:
      alerts:
        labels:
          - car
          - person
      detections:
        labels:
          - car
          - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 2
  dom2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dom2_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/dom2_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: dom2_hq
      quality: 1
    webui_url: "http://192.168.108.122:8899/"
    motion:
      mask: []
    zones:
      kacheli:
        coordinates: 421,204,419,112,523,111,567,200
        inertia: 5
        loitering_time: 3
        objects:
          - person
      dom2_tropinka:
        coordinates: 333,127,382,127,488,360,383,360
        inertia: 5
        loitering_time: 2
        objects:
          - person
      lavka:
        coordinates: 81,200,282,196,282,360,34,360
        inertia: 5
        loitering_time: 2
        objects:
          - person
    review:
      alerts:
        labels:
          - person
      detections:
        labels:
          - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 3
  street:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/street_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/street_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: street_hq
      quality: 1
    motion:
      mask: []
    zones:
      u_okna:
        coordinates: 0,360,0,194,112,310,90,360
        inertia: 5
        objects:
          - person
      za_zaborom:
        coordinates: 310,128,354,118,401,360,315,360
        inertia: 5
        objects:
          - person
      pod_oknami:
        coordinates: 201,153,297,149,282,360,97,360
        inertia: 5
        objects:
          - person
    review:
      alerts:
        labels:
          - person
        required_zones:
          - u_okna
          - za_zaborom
          - pod_oknami
      detections:
        labels:
          - person
        required_zones:
          - u_okna
          - za_zaborom
          - pod_oknami
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      quality: 100
    birdseye:
      order: 4

ui:
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"

telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    amd_gpu_stats: False
    intel_gpu_stats: True
    network_bandwidth: False
  version_check: True

camera_groups:
  outside:
    cameras:
      - gates
      - dvor_gates
      - dom2
      - street
      - door
    icon: LuCar
    order: 0