# yaml-language-server: $schema=https://frigate.skynerv.com/api/config/schema.json
mqtt:
  enabled: True
  host: mosquitto.home.svc.cluster.local
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 30
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: yuv
  width: 640
  height: 640
database:
  path: /data/frigate.db
audio:
  enabled: True
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8
    scream:
      threshold: 0.8
    yell:
      threshold: 0.8
    bark:
      threshold: 0.8
    fire_alarm:
      threshold: 0.8
logger:
  default: warning
  logs:
    frigate.event: debug
birdseye:
  enabled: True
  restream: False
  width: 1920
  height: 1080
  quality: 1
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-nvidia-h264
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p -an
    record: preset-record-generic-audio-copy
detect:
  width: 640
  height: 360
  fps: 5
  enabled: True
objects:
  track:
    - person
    - dog
    - car
    - bus
    - cat
record:
  enabled: True
  expire_interval: 60
  sync_recordings: True
  retain:
    days: 14
    mode: all
  export:
    timelapse_args: "-vf setpts=0.04*PTS -r 30"
  events:
    # pre_capture: 5
    # post_capture: 5
    retain:
      default: 30
      mode: active_objects
snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 14
    objects:
      person: 30
      car: 30
  quality: 90
go2rtc:
  streams:
    gates_hq:
      - ffmpeg:rtsp://admin:12332145@192.168.108.175:8554/Streaming/Channels/101#video=copy#audio=aac
    # gates_lq:
    #   - rtsp://admin:12332145@192.168.108.103:8554/Streaming/Channels/102
    #   - "ffmpeg:gates_lq#video=copy#audio=aac"
    door_hq:
      - ffmpeg:rtsp://user:12332145@192.168.108.197:554/ch0_0#video=h264#hardware=cuda#audio=aac
    # door_lq:
    #   - rtsp://user:12332145@192.168.108.197:554/ch0_1
    #   - "ffmpeg:door_lq#video=h264#hardware=cuda#audio=aac"
    dvor_gates_hq:
      - ffmpeg:rtsp://user:12332145@192.168.108.150:554/ch0_0#video=h264#hardware=cuda#audio=aac
    # dvor_gates_lq:
    #   - rtsp://user:12332145@192.168.108.150:554/ch0_1
    #   - "ffmpeg:dvor_gates_lq#video=h264#hardware=cuda#audio=aac"
    dom2_hq:
      - ffmpeg:rtsp://user:12332145@192.168.108.122:554/ch0_0#video=h264#hardware=cuda#audio=aac
    # dom2_lq:
    #   - rtsp://user:12332145@192.168.108.122:554/ch0_1
    #   - "ffmpeg:dom2_lq#video=h264#hardware=cuda#audio=aac"
  webrtc:
    candidates:
      - 192.168.108.55:8555
      - stun:8555
cameras:
  gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
        # - path: rtsp://localhost:8554/gates_hq
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    live:
      stream_name: gates_hq
      quality: 1
    webui_url: ""
    zones:
      inside_gates:
        coordinates: 546,360,640,360,640,267,538,182,437,272
        inertia: 5
        objects:
          - person
          - dog
          - car
      entryway:
        coordinates: 419,89,396,46,161,154,164,224
        inertia: 32
        objects:
          - car
          - bus
      guests:
        coordinates: 495,189,469,143,348,239,369,303
        inertia: 35
        objects:
          - person
    motion:
      mask:
        - 0,49,84,0,592,0,437,82,375,42,174,127,194,206,0,310
        - 293,360,342,317,356,202,456,133,489,139,530,89,563,91,640,0,591,0,439,80,0,318,0,360
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 0
  door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/door_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
        # - path: rtsp://localhost:8554/door_hq
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    live:
      stream_name: door_hq
      quality: 1
    webui_url: "http://192.168.108.197:8899/"
    motion:
      mask: []
    zones:
      near_the_door:
        coordinates: 212,360,515,360,517,326,257,318
        inertia: 10
        objects:
          - person
          - dog
          - car
      dvor:
        coordinates: 541,148,410,142,360,170,275,299,519,305
        inertia: 10
        objects:
          - car
          - person
      tropinka:
        coordinates: 598,202,576,52,553,51,550,201
        inertia: 10
        objects:
          - person
          - dog
      parkovka:
        coordinates: 552,141,538,21,366,33,363,138
        inertia: 10
        objects:
          - person
          - dog
      sad:
        coordinates: 348,195,326,0,68,67,0,89,0,360,187,360
        inertia: 10
        objects:
          - person
          - dog
          - cat
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 1
  dvor_gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dvor_gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
        # - path: rtsp://localhost:8554/dvor_gates_hq
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    live:
      stream_name: dvor_gates_hq
      quality: 1
    webui_url: "http://192.168.108.150:8899/"
    motion:
      mask: []
    zones:
      inside_gates:
        coordinates: 145,166,328,168,319,33,194,40
        inertia: 10
        objects:
          - person
          - dog
          - car
      at_the_door:
        coordinates: 0,307,66,360,90,301,121,219,110,175,51,177
        inertia: 10
        objects:
          - person
      in_the_garden:
        coordinates: 640,360,640,163,563,100,357,80,413,360
        inertia: 10
        objects:
          - person
      driveway:
        coordinates: 89,360,333,360,321,231,136,228
        inertia: 10
        objects:
          - person
          - car
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 2
  dom2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dom2_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
        # - path: rtsp://localhost:8554/dom2_hq
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    live:
      stream_name: dom2_hq
      quality: 1
    webui_url: "http://192.168.108.122:8899/"
    motion:
      mask: []
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 3
ui:
  live_mode: mse
  use_experimental: False
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"
telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    amd_gpu_stats: False
    intel_gpu_stats: False
    network_bandwidth: False
  version_check: True
