# yaml-language-server: $schema=https://frigate.skynerv.com/api/config/schema.json
mqtt:
  enabled: True
  host: mosquitto.home.svc.cluster.local
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 30
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: yuv
  width: 640
  height: 640
database:
  path: /data/frigate.db
audio:
  enabled: True
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8
    scream:
      threshold: 0.8
    yell:
      threshold: 0.8
    bark:
      threshold: 0.8
    fire_alarm:
      threshold: 0.8
logger:
  default: warning
  logs:
    frigate.event: debug
birdseye:
  enabled: True
  restream: False
  width: 1920
  height: 1080
  quality: 1
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-nvidia-h264
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p -an
    record: preset-record-generic-audio-copy
detect:
  width: 640
  height: 360
  fps: 10
  enabled: True
objects:
  track:
    - person
    - dog
    - car
    - bus
    - cat
record:
  enabled: True
  expire_interval: 60
  sync_recordings: True
  retain:
    days: 30
    mode: all
  export:
    timelapse_args: "-vf setpts=0.04*PTS -r 30"
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 30
      mode: active_objects
snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 30
    objects:
      person: 30
      car: 30
  quality: 90
go2rtc:
  streams:
    gates_hq:
      - rtsp://admin:12332145@192.168.108.104:554/stream1
      - "ffmpeg:gates_hq#audio=aac"
    gates_lq:
      - rtsp://admin:12332145@192.168.108.104:554/stream2
      - "ffmpeg:gates_lq#audio=aac"
    door_hq:
      - ffmpeg:rtsp://user:12332145@192.168.108.101:554/ch0_0#video=h264#hardware#audio=aac
    door_lq:
      - ffmpeg:rtsp://user:12332145@192.168.108.101:554/ch0_1#video=h264#hardware#audio=aac
    dvor_gates_hq:
      - rtsp://admin:12332145@192.168.108.210:554/stream1
      - "ffmpeg:dvor_gates_hq#audio=aac"
    dvor_gates_lq:
      - rtsp://admin:12332145@192.168.108.210:554/stream2
      - "ffmpeg:dvor_gates_lq#audio=aac"
    dom2_hq:
      - ffmpeg:rtsp://user:12332145@192.168.108.190:554/ch0_0#video=h264#hardware=cuda#audio=aac
    dom2_lq:
      - ffmpeg:rtsp://user:12332145@192.168.108.190:554/ch0_1#video=h264#hardware=cuda#audio=aac
    street_hq:
      - rtsp://admin:12332145@192.168.108.175:8554/Streaming/Channels/101
      - "ffmpeg:street_hq#video=copy#audio=aac"
    street_lq:
      - rtsp://admin:12332145@192.168.108.175:8554/Streaming/Channels/102
      - "ffmpeg:street_lq#video=copy#audio=aac"
  webrtc:
    candidates:
      - 192.168.108.55:8555
      - stun:8555
cameras:
  gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/gates_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: gates_hq
      quality: 1
    webui_url: ""
    zones:
      inside_gates:
        coordinates: 640,360,640,271,538,135,491,187,425,268
        inertia: 5
        objects:
          - person
          - dog
          - car
      entryway:
        coordinates: 363,64,294,44,90,172,120,244
        inertia: 40
        objects:
          - car
          - bus
      guests:
        coordinates: 463,196,418,141,282,267,346,318
        inertia: 50
        objects:
          - person
    motion:
      mask:
        - 0,75,0,49,84,0,466,0,358,62,294,37,94,168,118,246,0,336
        - 293,360,342,317,260,255,398,116,449,130,506,45,520,84,566,0,469,0,371,56,0,339,0,360
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 270
      quality: 100
    birdseye:
      order: 0
  door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/door_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/door_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: door_hq
      quality: 1
    webui_url: "http://192.168.108.150:8899/"
    motion:
      mask: []
    zones:
      near_the_door:
        coordinates: 159,360,515,360,517,326,210,317
        inertia: 10
        objects:
          - person
          - dog
          - car
      dvor:
        coordinates: 513,151,389,147,327,212,269,267,484,298
        inertia: 10
        objects:
          - car
          - person
      tropinka:
        coordinates: 576,203,591,47,553,51,539,197
        inertia: 10
        objects:
          - person
          - dog
      parkovka:
        coordinates: 516,171,516,94,395,80,363,138
        inertia: 10
        objects:
          - person
          - dog
      sad:
        coordinates: 337,193,326,0,68,67,0,89,0,360,125,360
        inertia: 10
        objects:
          - person
          - dog
          - cat
    objects:
      filters:
        dog:
          mask:
            - 470,360,502,257,515,156,384,136,333,207,162,360
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 1
  dvor_gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dvor_gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/dvor_gates_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: dvor_gates_hq
      quality: 1
    webui_url: "http://192.168.108.210:8899/"
    motion:
      mask: []
    zones:
      inside_gates:
        coordinates: 225,184,413,180,367,0,264,0,265,32,268,64
        inertia: 10
        objects:
          - person
          - car
      at_the_door:
        coordinates: 98,248,190,272,224,130,172,130
        inertia: 10
        objects:
          - person
      in_the_garden:
        coordinates: 640,360,640,65,464,0,374,34,466,360
        inertia: 10
        objects:
          - person
      driveway:
        coordinates: 138,360,450,360,410,186,219,191
        inertia: 10
        objects:
          - person
          - car
    objects:
      filters:
        dog:
          mask:
            - 440,360,372,0,284,0,161,360
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 2
  dom2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/dom2_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/dom2_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: dom2_hq
      quality: 1
    webui_url: "http://192.168.108.122:8899/"
    motion:
      mask: []
    zones:
      kacheli:
        coordinates: 421,204,419,112,523,111,567,200
        inertia: 10
        objects:
          - person
      dom2_tropinka:
        coordinates: 333,127,382,127,488,360,383,360
        inertia: 10
        objects:
          - person
      lavka:
        coordinates: 81,200,282,196,282,360,34,360
        inertia: 10
        objects:
          - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 3
  street:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/street_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/street_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: street_hq
      quality: 1
    webui_url: "https://192.168.108.104/"
    motion:
      mask: []
    zones:
      u_okna:
        coordinates: 0,360,0,194,112,310,90,360
        inertia: 10
        objects:
          - person
      za_zaborom:
        coordinates: 310,128,354,118,401,360,315,360
        inertia: 10
        objects:
          - person
      pod_oknami:
        coordinates: 201,153,297,149,282,360,97,360
        inertia: 10
        objects:
          - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
    birdseye:
      order: 4
ui:
  live_mode: mse
  use_experimental: False
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"
telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    amd_gpu_stats: False
    intel_gpu_stats: False
    network_bandwidth: False
  version_check: True
