mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: mosquitto.home.svc.cluster.local
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: "{FRIGATE_MQTT_USERNAME}"
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: "{FRIGATE_MQTT_PASSWORD}"
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  # tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  # tls_client_cert: /path/to/client.crt
  # tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  # tls_insecure: true
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 30

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  tensorrt:
    type: tensorrt
    device: 0
  # Required: name of the detector
  # cpu_detector:
    # Required: type of the detector
    # Frigate provided types include 'cpu', 'edgetpu', 'openvino' and 'tensorrt' (default: shown below)
    # Additional detector types can also be plugged in.
    # Detectors may require additional configuration.
    # Refer to the Detectors configuration page for more information.
    # type: cpu
model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: yuv
  width: 640
  height: 640

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /data/frigate.db

# Optional: model modifications
# model:
#   # Optional: path to the model (default: automatic based on detector)
#   path: /edgetpu_model.tflite
#   # Optional: path to the labelmap (default: shown below)
#   labelmap_path: /labelmap.txt
#   # Required: Object detection model input width (default: shown below)
#   width: 320
#   # Required: Object detection model input height (default: shown below)
#   height: 320
#   # Optional: Object detection model input colorspace
#   # Valid values are rgb, bgr, or yuv. (default: shown below)
#   input_pixel_format: rgb
#   # Optional: Object detection model input tensor format
#   # Valid values are nhwc or nchw (default: shown below)
#   input_tensor: nhwc
#   # Optional: Object detection model type, currently only used with the OpenVINO detector
#   # Valid values are ssd, yolox, yolov5, or yolov8 (default: shown below)
#   model_type: ssd
#   # Optional: Label name modifications. These are merged into the standard labelmap.
#   labelmap:
#     2: vehicle

# Optional: Audio Events Configuration
# NOTE: Can be overridden at the camera level
audio:
  # Optional: Enable audio events (default: shown below)
  enabled: True
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8
    scream:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8
    yell:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8
    bark:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8
    fire_alarm:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
birdseye:
  enabled: True
  restream: False
  width: 1920
  height: 1080
  quality: 1
  mode: motion
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-nvidia-h265
  input_args: preset-rtsp-restream
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p -an
    record: preset-record-generic-audio-copy
detect:
  width: 640
  height: 360
  fps: 10
  enabled: True
objects:
  track:
    - person
    - dog
    - car
    - bus
motion:
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.01
  frame_height: 150
  improve_contrast: True
record:
  enabled: True
  expire_interval: 60
  sync_recordings: True
  retain:
    days: 30
    mode: all
  export:
    timelapse_args: "-vf setpts=0.04*PTS -r 30"
  events:
    retain:
      default: 30
      mode: active_objects
snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 30
    objects:
      person: 30
  quality: 90
go2rtc:
  streams:
    gates_hq:
      - rtsp://admin:12332145@192.168.108.103:8554/Streaming/Channels/101
      - "ffmpeg:gates_hq#video=copy#audio=aac"
      # - "ffmpeg:rtsp://admin:12332145@192.168.108.103:8554/Streaming/Channels/101#video=h265#hardware#audio=copy#audio=aac"
    gates_lq:
      - rtsp://admin:12332145@192.168.108.103:8554/Streaming/Channels/102
      - "ffmpeg:gates_lq#video=copy#audio=aac"
      # - "ffmpeg:rtsp://admin:12332145@192.168.108.103:8554/Streaming/Channels/102#video=h265#hardware#audio=copy#audio=aac"
    door_hq:
      - rtsp://192.168.108.197:554/user=admin_password=A2DyfFrG_channel=0_stream=0&onvif=0.sdp?real_stream
      - "ffmpeg:door_hq#video=copy#audio=aac"
    door_lq:
      - rtsp://192.168.108.197:554/user=admin_password=A2DyfFrG_channel=0_stream=1&onvif=0.sdp?real_stream
      - "ffmpeg:door_lq#video=copy#audio=aac"
  webrtc:
    candidates:
      - 192.168.108.55:8555
      - stun:8555
live:
  stream_name: gates_hq
  quality: 1
cameras:
  gates:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/gates_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/gates_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    best_image_timeout: 60
    webui_url: ""
    zones:
      inside_gates:
        coordinates: 546,360,640,360,640,267,538,182,437,272
        inertia: 5
        objects:
          - person
          - dog
          - car
      entryway:
        coordinates: 419,89,396,46,161,154,164,224
        inertia: 32
        objects:
          - car
          - bus
      guests:
        coordinates: 495,189,469,143,348,239,369,303
        inertia: 70
        objects:
          - person
    motion:
      mask:
        - 0,49,84,0,592,0,437,82,375,42,174,127,194,206,0,310
        - 293,360,342,317,356,202,456,133,489,139,530,89,563,91,640,0,591,0,439,80,0,318,0,360
  door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/door_hq
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/door_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    best_image_timeout: 60
    webui_url: ""
    motion:
      mask: []
    zones:
      near_the_door:
        coordinates: 212,360,515,360,517,326,257,318
        inertia: 5
        objects:
          - person
          - dog
          - car
      dvor:
        coordinates: 541,148,410,142,360,170,275,299,519,305
        inertia: 5
        objects:
          - car
          - person
      tropinka:
        coordinates: 598,202,576,52,553,51,550,201
        inertia: 5
        objects:
          - person
      parkovka:
        coordinates: 552,141,538,21,366,33,363,138
        inertia: 5
        objects:
          - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 270
      quality: 100
      required_zones: []
    birdseye:
      order: 0
ui:
  live_mode: mse
  use_experimental: False
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"
telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    amd_gpu_stats: False
    intel_gpu_stats: False
    network_bandwidth: False
  version_check: True
