---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-ollama
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: ai
  path: "./kubernetes/apps/ai/ollama/backend"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-ollama-web-ui
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: ai
  path: "./kubernetes/apps/ai/ollama/ui"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: ai-ollama
