---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama
  namespace: flux-system
spec:
  targetNamespace: ai
  interval: 10m
  path: "./kubernetes/apps/ai/ollama/backend"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui
  namespace: flux-system
spec:
  targetNamespace: ai
  interval: 10m
  path: "./kubernetes/apps/ai/ollama/ui"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: ollama