apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
    namespace: service
stringData:
  SMTP_RELAY_HOSTNAME: ${SMTP_RELAY_HOSTNAME}
  SMTP_RELAY_SERVER: ${SMTP_RELAY_SERVER}
  SMTP_RELAY_USERNAME: ${SMTP_RELAY_USERNAME}
  SMTP_RELAY_PASSWORD: ${SMTP_RELAY_PASSWORD}