---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 568

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/jellyfin
              tag: 10.8.11
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 500000000
            resources:
              requests:
                memory: 9248M
              limits:
                nvidia.com/gpu: 1
                memory: 9248M

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host1 dh.${SECRET_DOMAIN}
            paths:
              - path: /jellyfin/
                service:
                  name: main
                  port: http
          - host: &host2 jelly.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host1
              - *host2

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: "/opt/docker/appdata/jellyfin/config"
        advancedMounts:
          main:
            main:
              - path: /config
      media:
        existingClaim: media-storage
        globalMounts:
          - path: /media

      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode