---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 568
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 2024050906@sha256:28fcb03500b13ec38d0c2a70640e0d574dfa244648b90a7d90f62d0e577e10ef
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 1G
              JELLYFIN_FFmpeg__analyzeduration: 200M
            resources:
              requests:
                memory: 9248M
              limits:
                nvidia.com/gpu: 1
                memory: 9248M
    service:
      main:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.108.77
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host1 jelly.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host1
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      media:
        existingClaim: media-storage
        globalMounts:
          - path: /media