---
kubernetes:
  children:
    controllers:
      hosts:
        "laik":
          ansible_user: "root"
          ansible_host: "192.168.108.149"
    workers:
      hosts:
        "tau":
          ansible_user: "root"
          ansible_host: "192.168.108.199"
        "weilai":
          ansible_user: "root"
          ansible_host: "192.168.108.209"
