---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: samba-operator
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: samba
  path: "./config/default"
  prune: true
  timeout: 15m