---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-outputs-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-fast
