---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 7.3.7
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    replicas: 1
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            disableDeletion: false
            editable: true
            folder: ""
            options:
              path: /var/lib/grafana/dashboards/default
            orgId: 1
            type: file
          - name: "flux"
            orgId: 1
            folder: "Flux"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/flux
          - name: "kubernetes"
            orgId: 1
            folder: "Kubernetes"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/kubernetes
          - name: "networking"
            org_id: 1
            folder: "Networking"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/networking
          - name: "system"
            orgId: 1
            folder: "System"
            type: file
            disableDeletion: false
            editable: true
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/system
          - name: "victoria-metrics"
            orgId: 1
            folder: "VicoriaMetrics"
            type: file
            disableDeletion: false
            editable: true
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/vm
          - name: "nginx"
            orgId: 1
            folder: "Nginx"
            type: file
            disableDeletion: false
            editable: true
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/nginx
          - name: "storage"
            orgId: 1
            folder: "Storage"
            type: file
            disableDeletion: false
            editable: true
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/storage
          - name: "loki"
            orgId: 1
            folder: "Loki"
            type: file
            disableDeletion: false
            editable: true
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/loki
    dashboards:
      default:
        ntfy:
          url: https://raw.githubusercontent.com/binwiederhier/ntfy/main/examples/grafana-dashboard/ntfy-grafana.json
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        node-feature-discovery:
          url: https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/master/examples/grafana-dashboard.json
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
      storage:
        minio:
          # renovate: depName="MinIO Dashboard"
          gnetId: 13502
          revision: 26
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        redis:
          # renovate: depName="Redis"
          gnetId: 12776
          revision: 2
          datasource: Prometheus
        smartmon:
            gnetId: 10530
            revision: 1
            datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        longhorn:
          gnetId: 13032
          revision: 1
          datasource:
            - { name: DS_RANCHER_MONITORING, value: Prometheus }
      system:
        node-exporter-full:
          gnetId: 1860
          revision: 31
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        cert-manager:
          url: https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json
          datasource: VictoriaMetrics
        spegel:
          # renovate: depName="Spegel"
          gnetId: 18089
          revision: 1
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
      victoria-metrics:
        cluster:
          gnetId: 11176
          revision: 34
          datasource:
            - { name: ds, value: Prometheus }
        cluster-native:
          gnetId: 11831
          revision: 6
          datasource: VictoriaMetrics
        vmagent:
          gnetId: 12683
          revision: 14
          datasource:
            - { name: ds, value: Prometheus }
      flux:
        # TODO: fix
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/cluster.json
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/control-plane.json
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        # flux-logs:
        #   url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/logs.json
        #   datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
      nginx:
        nginx:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
          datasource:
          - { name: DS_PROMETHEUS, value: Prometheus }
        nginx-request-handling-performance:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
          datasource:
          - { name: DS_PROMETHEUS, value: Prometheus }
        ingress-nginx-external:
          gnetId: 14314
          revision: 2
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        ingress-nginx-request-handling-performance:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        ingress-nginx:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
      networking:
        cilium-agent:
          gnetId: 16611
          revision: 1
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        cilium-operator:
          gnetId: 16612
          revision: 1
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        hubble:
          gnetId: 16613
          revision: 1
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        hubble-dns:
          gnetId: 16612
          revision: 37
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        hubble-overview:
          gnetId: 16612
          revision: 39
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        cloudflared:
          # renovate: depName="Cloudflare Tunnels (cloudflared)"
          gnetId: 17457
          revision: 6
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - { name: Alertmanager, orgId: 1 }
          - { name: Loki, orgId: 1 }
          - { name: Prometheus, orgId: 1 }
        datasources:
          - name: Prometheus
            type: prometheus
            uid: prometheus
            access: proxy
            # url: http://thanos-query-frontend.monitoring.svc.cluster.local:9090
            url: http://vmselect-victoria-metrics.observability.svc:8481/select/0/prometheus
            jsonData:
              prometheusType: Thanos # Prometheus for victoria-metrics
            isDefault: true
          - access: proxy
            name: VictoriaMetrics
            type: victoriametrics-datasource
            url: http://vmselect-victoria-metrics.observability.svc:8481/select/0/prometheus
          - name: Loki
            type: loki
            uid: loki
            access: proxy
            url: http://loki-gateway.observability.svc.cluster.local
            jsonData:
              maxLines: 250
          - name: Alertmanager
            type: alertmanager
            uid: alertmanager
            access: proxy
            url: http://vmalertmanager-victoria-metrics.observability.svc.cluster.local:9093
            jsonData:
              implementation: prometheus
    envFromSecrets:
      - name: grafana-env
    grafana.ini:
      server:
        root_url: https://grafana.${SECRET_DOMAIN}
      auth:
        signout_redirect_url: "https://authentik.company/application/o/grafana/end-session/"
        oauth_auto_login: true
      auth.basic:
        disable_login_form: false
      auth.generic_oauth:
        enabled: true
        name: authentik
        # client_id: abcd # Set by env vars
        # client_secret: abcd # Set by env vars
        scopes: "openid profile email"
        empty_scopes: false
        auth_url: https://${SSO_DOMAIN_PREFIX}.${SECRET_DOMAIN}/application/o/authorize/
        token_url: https://${SSO_DOMAIN_PREFIX}.${SECRET_DOMAIN}/application/o/token/
        api_url: https://${SSO_DOMAIN_PREFIX}.${SECRET_DOMAIN}/application/o/userinfo/
        login_attribute_path: preferred_username
        groups_attribute_path: groups
        name_attribute_path: name
        role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
      plugins:
        # Why VictoriaMetrics datasource is unsigned: https://github.com/VictoriaMetrics/grafana-datasource/blob/main/README.md#why-victoriametrics-datasource-is-unsigned
        allow_loading_unsigned_plugins: victoriametrics-datasource
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - vonage-status-panel
      - "https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.5.0/victoriametrics-datasource-v0.5.0.zip;victoriametrics-datasource"
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: "internal"
      hosts:
        - &host grafana.${SECRET_DOMAIN}
      tls:
        - hosts:
          - *host
    persistence:
      type: pvc
      enabled: true
      storageClassName: longhorn-fast
      accessModes:
        - ReadWriteOnce
      size: 1Gi