---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
stringData:
    SONARR__API_KEY: ${SONARR_API_KEY}
    SONARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
    SONARR__POSTGRES_PORT: "5432"
    SONARR__POSTGRES_USER: &dbUser pgsonarr
    SONARR__POSTGRES_PASSWORD: &dbPass ${SONARR_PG_PASSWORD}
    SONARR__POSTGRES_MAIN_DB: sonarr_main
    SONARR__POSTGRES_LOG_DB: sonarr_log
    PUSHOVER_TOKEN: ${SONARR_PUSHOVER_TOKEN}
    PUSHOVER_USER_KEY: ${PUSHOVER_USER_KEY}
    INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
    INIT_POSTGRES_HOST: *dbHost
    INIT_POSTGRES_USER: *dbUser
    INIT_POSTGRES_PASS: *dbPass
    INIT_POSTGRES_SUPER_PASS: ${POSTGRES_SUPER_PASS}
