---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: victoria-crd-source
  namespace: flux-system
spec:
  interval: 30m
  # renovate: datasource=github-releases
  url: https://github.com/VictoriaMetrics/operator.git
  ref:
    tag: v0.41.2
  ignore: |
    # exclude all
    /*
    # path to crds
    !/config/crd/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-operator-crds
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: observability
  path: "/config/crd/"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: victoria-crd-source
  interval: 30m
  retryInterval: 1m
  timeout: 3m