apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-crds
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./config/crd/
  prune: true
  sourceRef:
    kind: GitRepository
    name: victoria-crd-source
  targetNamespace: observability