---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-operator-crds
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: observability
  path: "./config/crd/"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: victoria-crd-source
  interval: 30m
  retryInterval: 1m
  timeout: 3m