apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:JxQ4n8tq32lpwP99lLga52315CTS+E+ZP95ZN2oiX7Fv7m+KdmAJfQ==,iv:+7HStArSthv7M4uu4zCcs+eH1HWyflCuqofOW1JXdXc=,tag:e77rZLsom4GlHEKsB2u82A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdktnSXUxNEp2ZDV2WS9P
            K0Fsd1hWK2hRSUErQXZHTFhCWU1sbGxqaUM0ClROSWVxVnZJT2RFWU5XNTNHTENV
            ZUdyTVVEYmMvNlkrTHVBeUgvemMvVWsKLS0tIFFTTHhoNkxySjZ0Wk9MWnZDSXRJ
            Q3B3YkJINEplQTJOQ1ZUK2Z5SmYzbXcKwd1c9ogrcwyCz+RgFBWTCQ7CoaAkY7Zs
            YBc5Y3hAbl/cI0o7O9LT1aoWYvOBY4P0EBL9w6sJxFmHu8ivf3PRJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T22:25:33Z"
    mac: ENC[AES256_GCM,data:lKhz4W5FFNixi/ehrRvLG3OUoXosvRvDJip7qIubruTZvCmib+wd16larytaUfHYRfrBuNyzFxXYyyQgEPZbqPwbcbVjLggUtxFg3GhSfaJdqyXfOU+gjCx00Gh7S7hGTTJ0e+u282WUd4PSrXScg36zHIuKUy4IQempSw7K/Us=,iv:2DV95jYt+aafByTReetvFHqMkzPTFQqWpIT9MtrwAwI=,tag:2n4oktXHK2b55bdTsXkpqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
