apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:eARznKilFhH5863WWYNv/VJV0vqivN6RkKgdkXIFSYnN3Dk2P8oSgw==,iv:I6l03oQz+hO1MnplR1z0lDl0nE1h1gHsKeC5/B+9UQg=,tag:4Bxnw6rB0WJgYGYTBg4O6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQmdxM3Q0Und5WFZSM042
            VDJZcmxpRjgwcWdUd2RMMXlaZ1ByWmxiUFV3CjhSbHoxak9hZElZdlJhU2ZjeFEz
            NmxGYmNpQXpUVm1RMHBLWWZ4bnp1NEkKLS0tIDVrYmJnTGJBTUl5TzFJd3pDOEdm
            ek0zai91eW8wS1dzblJSZy9UODIra2sK5snYVy/o/xsMqpd7Nkyn+RyPLnbgcNWQ
            wdGLlFTAr+eYcp9bxnoY46f+JfVOy0tV64IR9a2Pp3iXoiXEwNC9jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T21:31:19Z"
    mac: ENC[AES256_GCM,data:mBhJCkZxqvSqhl4ry6JAZ2bodv8f2rpTve4BDDBpFvkudZ3fFYclUk8c++VKwOQAv2CMDI0wctZk0uQaN46K4XZiaJBm2nra1i0xXEkhRspbTZFVO0eWi+JD9GJjf6OFhcIuXIrnx/ekMVKgsr8UNfQ8gvZL6F5dnum85z395s0=,iv:W2EWYa9tS2U9RfGigXGyJj7K7o6WWykElH8w08zhzLM=,tag:1WYAPjbIHUSJM2JaHZm5pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
