---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./configmap.yaml
  - ./secret.sops.yaml
  - ./machine-learning
  - ./server
  - ../../../../templates/gatus/external