apiVersion: v1
kind: Secret
metadata:
    name: immich
stringData:
    #ENC[AES256_GCM,data:es1wDVDasg==,iv:iPW4f/RL1D0N1sSnzL8YpT679M3Pmxtue6ynYtWeZX8=,tag:8I2NAzW0b/mdI2wTekvxKQ==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:MfacrKRghLA=,iv:hx5cMuOrPEc3fg6jw+j7nHoM+Ni6Iqr+5Ztqo0TNehg=,tag:/0AMsfFpvyQZs1mFB++FcQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:mHdCVVEr+0affoCdnq0zeAZyDRJWJn1+wGbMaeDdOj8fL3PnVLo1nQ==,iv:QkTz9AjWROlhu1id4pH/VzOY6fCe9Vy2ldjFq+ZDFRw=,tag:4m1yYHVBH2jnzeBbd3PP+Q==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Q56844u4akdKxw==,iv:wtUScO5vCqP02C9ysKCFLFBygErDsaMmhpFcMJNp3qc=,tag:Ocf/nknPiNXCg/zrQ+D5OA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:LPjC5Vrmw4xOMkos293T2b+Z4wQ=,iv:QstByJaphOCLthDKRmm16rm/KTlDyc9pXCszUtOSpfY=,tag:i8vFxbTqU89oxbAPYPo6fg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ytSFSyO+hE5KiTBTBsMxXkeiY/7oTmU=,iv:jm3SAZHI5eaVYPWiMNtD9635XENVue52fx2hea+5SP4=,tag:/eL1PL00hApQPxdcPGfbkA==,type:str]
    #ENC[AES256_GCM,data:xRZV2uxW6WyPf41HxJE=,iv:c0uFQQgBzcYvp+3ujmpC+c2Tk/p+N8l28Ik31fxi9dY=,tag:jQEw+BsFmHPZyMg8duAorg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:1fQWWoqmvUA=,iv:Hyh3NDUkAiPBUZq6LSs/ILqTir5nCzeDMZLobkuuz7Y=,tag:yZmFkvOpG0D3XEdsMsb3mQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:hGGdOkLqdvGZ6OMP8Gocu91aKqxQUGSrI0SUqfEMwbwDB0PsVrPaeQ==,iv:IoFfffv6oyH/EhgUPepBKatrGbgo6AsSiKbnMVbLUDA=,tag:ksB69BJAiT4H7cHRj0TNvg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:lwutlUQ36uJ3WA==,iv:vLlWucbVUf1zFpzxwHS+rxJdoSlXu1Vpc5avLVqEzD8=,tag:MjAhuwNwd/Syo9txaNxPHA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:H2QaQMo5cF6d+Wg07ztB/mySJm4=,iv:Mz4zQwX4JXI0pV9lJz5OtSPdHq7vef5Gw/KOOeefC2o=,tag:QA4UdoOgzbZQSx2GOOW2nA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:CzgD7X5XPHfAosMK3cM4eSuB08mflAxZXg==,iv:cK5P4AYQjObRHXGYpeWCe84kP63XmQBUbZ1kHLiW0oM=,tag:mIX2gCOd/EudMFU89FmBkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRTloWkkrOVUvWmhoaVdM
            OW45N3FDd0F3WlF0QWc5eDRja1oyNW5xTXpFCno0dzhmSWgrd2VwUGw3YVpuN2N2
            eFhXTEI4c0FxeVc1WFBQNkNPTFJEbFEKLS0tICtDRzJ0eTZjOVluV2R4WGZwd3ZS
            L3FmQzByN1RYUWk0RTA2N0h3NU13dDQKqr3SQSwn4dZokzOOMvfXq43X8VH3W86D
            xA/LmESCF4Ha21oloczcKZ+URH/4oWoK8HvXGcDVnIH0SSQ1gJKuog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T23:48:46Z"
    mac: ENC[AES256_GCM,data:CNJ7ta4FO6sBU+RzP7OoF5pJ4S+PGD8317rxnTTkmE+Q6B3uy5WxZ0DtEgLg0eFzdmbHfpPPmuy7/OtjT4bI0BdT+AXJgqI4TmatA1KKmVQKn4HXjoF/Ov5cqcY3IwSdQp87k6rcoIIHZa4/hmGApLuJf1JTERqsnmKv0/5hbgQ=,iv:xNs7RynZO5L9HQBr1P7ZAfkUtz6DnmWByaXMa7YCr8Q=,tag:3gpRn7tE6810iQQ49Ms0tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
