apiVersion: v1
kind: Secret
metadata:
    name: immich
stringData:
    #ENC[AES256_GCM,data:es1wDVDasg==,iv:iPW4f/RL1D0N1sSnzL8YpT679M3Pmxtue6ynYtWeZX8=,tag:8I2NAzW0b/mdI2wTekvxKQ==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:MfacrKRghLA=,iv:hx5cMuOrPEc3fg6jw+j7nHoM+Ni6Iqr+5Ztqo0TNehg=,tag:/0AMsfFpvyQZs1mFB++FcQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:mHdCVVEr+0affoCdnq0zeAZyDRJWJn1+wGbMaeDdOj8fL3PnVLo1nQ==,iv:QkTz9AjWROlhu1id4pH/VzOY6fCe9Vy2ldjFq+ZDFRw=,tag:4m1yYHVBH2jnzeBbd3PP+Q==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:l+LWTYombrZ2XYNent3DYUL3o2CC5Q==,iv:Km316rCm/V3abawJDVdbNHGKmTvRKQeu7yRgDpRPM68=,tag:qQOOdkLgoIHrbHUNPdEFyw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:qoYOmxSp1RKFRHU9ZrmbioFhepVA0w==,iv:xPq5gnZKADdquBATsBvWuqVcfu0FiVpRp3RNMNhqHR0=,tag:FQ5KNoKZd5oMTRt1OLrSOw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Hjh9077wgBsFMt4kiYN4X1SsfEU=,iv:+AJ0/BEWsfr59sT1+Kag9fiQt4GhBn2jXQNtcWkUm+M=,tag:9NhokJ0xpX01FgBdhhy4ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRTloWkkrOVUvWmhoaVdM
            OW45N3FDd0F3WlF0QWc5eDRja1oyNW5xTXpFCno0dzhmSWgrd2VwUGw3YVpuN2N2
            eFhXTEI4c0FxeVc1WFBQNkNPTFJEbFEKLS0tICtDRzJ0eTZjOVluV2R4WGZwd3ZS
            L3FmQzByN1RYUWk0RTA2N0h3NU13dDQKqr3SQSwn4dZokzOOMvfXq43X8VH3W86D
            xA/LmESCF4Ha21oloczcKZ+URH/4oWoK8HvXGcDVnIH0SSQ1gJKuog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T21:44:34Z"
    mac: ENC[AES256_GCM,data:XqlSxzzlJJV3oj73w1sJeJLUzZMJtH8WDEqKb/WfGh256lyZxgQ3tPHY8p3zqh+bQbbg+s21PsGQXioZ2y0Iw7EStD0pQT64+A4Elw3+o3EUf0ySKpAzsMXztruVfEsLbEaIrZTBNeOk+qT29AHU4RXsJ546tTbU9UO1m0ttjA4=,iv:yq9dRIiqC429l83nLN0VWGtg3rQZNSVFunVo1mepzxQ=,tag:lOKyY9wLuImn+XXOztMDsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
