---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    PROWLARR__API_KEY: ${PROWLARR_API_KEY}
    PROWLARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
    PROWLARR__POSTGRES_PORT: "5432"
    PROWLARR__POSTGRES_USER: &dbUser pgprowlarr
    PROWLARR__POSTGRES_PASSWORD: &dbPass ${PROWLARR_PG_PASSWORD}
    PROWLARR__POSTGRES_MAIN_DB: prowlarr_main
    PROWLARR__POSTGRES_LOG_DB: prowlarr_log
    INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
    INIT_POSTGRES_HOST: *dbHost
    INIT_POSTGRES_USER: *dbUser
    INIT_POSTGRES_PASS: *dbPass
    INIT_POSTGRES_SUPER_PASS: ${POSTGRES_SUPER_PASS}