---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sftpgo
spec:
  interval: 5m
  chart:
    spec:
      chart: sftpgo
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: skm
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Simferopol
    sftpd:
      enabled: true
    webdavd:
      enabled: true
    httpd:
      enabled: true
    ftpd:
      enabled: true
    config:
      data_provider:
        driver: "sqlite"
        name: "/config/db.sqlite"
        prefer_database_credentials: true
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      supplementalGroups:
        - 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-storage
      - name: sftpgo
        persistentVolumeClaim:
          claimName: sftpgo
    volumeMounts:
      - name: media-storage
        mountPath: /data
      - name: sftpgo
        subPath: configs/sftpgo
        mountPath: /config
      - name: sftpgo
        mountPath: /sftpgovol
    service:
      annotations:
        io.cilium/lb-ipam-ips: "192.168.108.11"
        external-dns.alpha.kubernetes.io/hostname: media.${SECRET_DOMAIN}
      type: LoadBalancer
    ui:
      ingress:
        enabled: true
        annotations: {}
        className: internal
        hosts:
          - host: sftpgo.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - sftpgo.${SECRET_DOMAIN}
            secretName: sftpgo-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftpgo-webdav
  namespace: media
  labels:
    app.kubernetes.io/name: sftpgo-webdav
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - webdav.${SECRET_DOMAIN}
      secretName: sftpgo-ingress-cert
  rules:
    - host: webdav.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: sftpgo
                port:
                  name: webdav
