---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sftpgo
spec:
  interval: 5m
  chart:
    spec:
      chart: sftpgo
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: skm
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Simferopol
    sftpd:
      enabled: true
    webdavd:
      enabled: true
    httpd:
      enabled: true
    ftpd:
      enabled: true
    config:
      # data_provider:
      #   driver: 'sqlite'
      #   name: '/config/db.sqlite'
      #   prefer_database_credentials: true
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      supplementalGroups:
        - 568
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    volumes:
    - name: media-storage
      persistentVolumeClaim:
        claimName: media-storage
    - name: sftpgo
      persistentVolumeClaim:
        claimName: sftpgo
    volumeMounts:
    - name: media-storage
      mountPath: /data
    # - name: sftpgo
    #   subPath: configs/sftpgo
    #   mountPath: /config
    # - name: sftpgo
    #   mountPath: /sftpgovol
    ui:
      ingress:
        enabled: true
        annotations: {}
        className: internal
        hosts:
        - host: sftpgo.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: ImplementationSpecific
        tls:
        - hosts:
          - sftpgo.${SECRET_DOMAIN}
          secretName: sftpgo-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftpgo-webdav
  namespace: media
  labels:
    app.kubernetes.io/name: sftpgo-webdav
spec:
  ingressClassName: internal
  tls:
  - hosts:
    - webdav.${SECRET_DOMAIN}
    secretName: sftpgo-ingress-cert
  rules:
  - host: webdav.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: sftpgo
            port:
              name: webdav
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftpgo-sftp
  namespace: media
  labels:
    app.kubernetes.io/name: sftpgo-sftp
spec:
  ingressClassName: internal
  tls:
  - hosts:
    - sftp.${SECRET_DOMAIN}
    secretName: sftpgo-ingress-cert
  rules:
  - host: sftp.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: sftpgo
            port:
              name: sftp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftpgo-ftp
  namespace: media
  labels:
    app.kubernetes.io/name: sftpgo-ftp
spec:
  ingressClassName: internal
  tls:
  - hosts:
    - ftp.${SECRET_DOMAIN}
    secretName: sftpgo-ingress-cert
  rules:
  - host: ftp.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: sftpgo
            port:
              name: ftp