apiVersion: v1
kind: Secret
metadata:
    name: loki-bucket
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:j2egLQ==,iv:lqQf0tRPXjJNQn2x4Hp5KDiWYfO9em1uwQcxT2pI/00=,tag:vGEu2Ft2dt5V3fQVpCo9aA==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:beIIWz5wEHOUyqLxFjs7E3a7oaQWSGsCPg==,iv:PX14ZcgND2W7Ci1bzCvAz+4fkoTdKwGf0pKH6m5enec=,tag:KRkmWcBZhjbPenS0aWnEhw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cLrf4A9dv18CI36HytyUHiY6,iv:NRlCl2UgXwAixLpYuPQ7SA7KmEyf4NWv1aG6jnuzjJM=,tag:f0yfhP051EOxOkoqDjaYng==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:78+Y70fRPh/TWCtGmRmhRyG3vCqgjw==,iv:BUPGBu6NmWG3o8D+X6x7UeirpRFOZ2zqeCMAH1rNmos=,tag:t43b40oYtU/q7y9LJRXEhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndHdkSjBoWW1ldUxxK0Zt
            ZTNLQmZlbjlBbjVZTG1OYWNUdHRqWmE1MlNzCmtBbWZCQXR4T045UERiVEFtdEto
            eHA2TSsrZEtITHlOTkdzYWJBRVh0RjAKLS0tIFY2Sk5EMVBRYWlmelkybzNoNW5x
            U1N4Z2g0cjlEd1laMUVZZlRuSHAvRTQK+lZmHrLlqzbYkbtLrO5IGjR7FQOCxAHD
            NXoMzY+8hMMx17nTnVgEgDP1qA0oR+qdwLJmTn+UBJS+3vTMZPg2vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T22:23:13Z"
    mac: ENC[AES256_GCM,data:9jvN8BX2C6lBbWHPKv3tQ3jJqT5Tl5ujqxRmFSVokCUEYpVfOujMKsWDcUU1nilmUXA9rX+diPWc9OPINMc223T/nKYWtmgK5yZJ2o+wgGEk0INGrULOblON1pIoYiRy0uMNuCCHx6GVhPdrDy91PFEqIq80WRWkMqTODTJn6nw=,iv:uTi4DqR+zBnjaJhInNYdoGA+4fV7EssDgH7dfHxFHr0=,tag:9aROyNCwQ3pMA9hLrrGmxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
