---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Ti
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-storage