---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 15500Gi
  storageClassName: longhorn-storage