---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Ti
  storageClassName: longhorn-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multimedia
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 101Gi
  storageClassName: hostpath