---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: scrypted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            supplementalGroups:
              - 65542
        containers:
          app:
            image:
              repository: ghcr.io/koush/scrypted
              tag: 20-jammy-full-v0.98.0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                nvidia.com/gpu: 1
                cpu: 13m
                memory: 1024Mi
              limits:
                nvidia.com/gpu: 1
                memory: 8192Mi
            securityContext:
              privileged: true
    service:
      app:
        controller: scrypted
        ports:
          http:
            port: 11080
          rebroadcast:
            port: 34135
    ingress:
      app:
        className: "internal"
        hosts:
          - host: &hostName scrypted.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName
    persistence:
      config:
        existingClaim: scrypted-config
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
      recs:
        existingClaim: suv-storage
        globalMounts:
          - path: /media
