---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-storage
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-iceberg
