---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-deepstack
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/ai/deepstack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: longhorn
  interval: 30m
  retryInterval: 1m
  timeout: 3m