---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  labels:
    app.kubernetes.io/name: harbor-registry
    app.kubernetes.io/instance: harbor
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi