apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
  name: smb-common
  namespace: storage
spec:
  network:
    publish: external
  podSettings:
    nodeSelector:
      "kubernetes.io/os": "linux"
      "kubernetes.io/arch": "amd64"