apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: exchange-storage
  namespace: storage
spec:
  shareName: Exchange
  storage:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: longhorn-storage
  browseable: true
  securityConfig: smb-domain-security
  commonConfig: smb-common
  readOnly: false
  scaling:
    availabilityMode: standard
status:
  serverGroup: smb-exchange