---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor-init
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        enabled: false
      tagging:
        type: cronjob
        cronjob:
          schedule: "@daily"
          timeZone: &timeZone Europe/Simferopol
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          init:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2@sha256:3436dfbbc2799332a01361e007e3b408d016cfc235261e1caccc65e6edadf516
            env:
              TZ: *timeZone
            envFrom:
              - secretRef:
                  name: harbor-init-secret
        pod:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
    service:
      main:
        enabled: false















    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2@sha256:3436dfbbc2799332a01361e007e3b408d016cfc235261e1caccc65e6edadf516

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
        main:
          ports:
            http:
              port: 8049