---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./gatus/ks.yaml
  - ./loki/ks.yaml
  - ./smartctl-exporter/ks.yaml
  # - ./unpoller/ks.yaml
  - ./vector/ks.yaml
  - ./victoria-metrics/ks.yaml
  - ./grafana/ks.yaml
  - ./ntfy/ks.yaml