apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BPDFeKsSLw2Dz/E=,iv:9ojwCCR1irLZkGgZZl9SOMbDtkLX+Hw66SJP5PVoxts=,tag:x2KoAqG4yNNo7uyE0COvCA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:318ebuxf2OqEVMiVaXVMWBQ=,iv:Mb/UodbJsEReSiyvMXERvM+HPMxPvNorU188UFdNw0k=,tag:NU/xt/ZbnrONcb1W714Q2w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zzNCv/LjOw7sQTQHbr2LP1TwtLyIXpHwtco+HDDEj6b7elT/,iv:aN2HVpjkgYp0/Xy6dL1Qv7H+udFCkF5Tn84GC8slCSo=,tag:8SfObCci4a+1N5aRwjWVMA==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:pRg0zri1OZ+VZV1humTa6UHHsoYXk7ZzM82lIDvq7JfQcyEg+eHnIlFwSTTDtlVWcOv/ZZDaxYLoHyYG,iv:rIPiy1ZsAs55lBYfkIoMGTjTztPKHKq0Euw7b05l68w=,tag:ucwDP4s0/pnxSIQ5jvPUZw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:mgjufe7mZZ75OkSYNMoZcGvvkEw=,iv:5JGR5JXBRcOProVxNKoWPzynoL7OD3US0a7vy27GDCk=,tag:2FQImm2jpHbAl4s2IajtOQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:K6HrcpKfdOHLThv847IoUjNoG6A=,iv:5giRbwe+Q2z+Z5ec+O8sdEZS3iqVWhVPjNQOhuMx9Eo=,tag:WydUkmN4/hQYFgdN9/T7gA==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:MnZhTBuY4vkVT6TkcUnrc3ao2yE=,iv:E/6U5lDcyi/mkIKQ991+zVKFiSpTFBfy8re0l4/XD8Y=,tag:eQfApf21m6M9msSSqZVrnQ==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:iOBmvCjsj7DFHA==,iv:1biCjPeXN5RwxGrKKd66i/xqwtASBErsJLM/1IqALIs=,tag:N+G1drFGaX2pXDCUaRZIkg==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:lDsmNeJGzceLDw==,iv:8erR+f2nulFNvl46xtZe6mL2Lk/OvfOkjPjq6RDXuxY=,tag:XbD6ow0BrJSrASzp2gAObw==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:BRMPnuoPvgSijA==,iv:3NIv9c+Wg1VZgRTnarYiUfjja6YSG/wnczcVHF2UypI=,tag:VpG6yc2ju0d57UbN7BEvQw==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:9/lbh6Rnemw=,iv:4B+OeffhGZ2KIomOo/zFjfSLG67DACLs6hEkUBwDNOU=,tag:JSn572Q1bNNZ/EOu4RLBBA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:J6FeJRD84iIRVtp0/91ktcrVAQ==,iv:8rL2/cs6k8uV8r3vsGR5HQpPOIAkpM4bIOq2hMwH5RQ=,tag:Elaz0v9yTAZ/8K9PAuuHOg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:yw6AjW0EXtjd,iv:31lrASRIL7FPYfI6aEX/78UdptK4jxrDBM1NxCgzKck=,tag:2ase/ip6sTOo4qT9ZnRCyw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:7Q/BxHHBRliqSg==,iv:AlMR/cmRHlxsAWwPTbfDj0rB6TO8lXlhCAKMvhHf3CM=,tag:xRXY2L1eIluZV/Q2BypgmA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:/GKNQ296d8YqjU7VVAY1RrRVcq5ZBsT+JkIt/mX3,iv:jpl/0670Ib+9XJx0fjOIqZFL91CKXeg8/JTajEZNht0=,tag:h5sms0Jw2WBA2BRhd4z50Q==,type:str]
    GATUS_PUSHOVER_TOKEN: ENC[AES256_GCM,data:fS6KBB3j5IZcbj+nnZneXXGMWfRRbtagzjWO6IYV,iv:T1XLyYdU32tM8G+OUGgJB3kL2REWcjvAMjgvk/2suq4=,tag:2GVVKpo4u1j9sSO2GRCy1Q==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:USKIMaJ+Uy9oMVWkuOeKcdTKEHBTbgjl7rFthpWO8ndBp989bb61p9xvu+4azw9TpdjXC//tyzdbUTwX3FA0Vg==,iv:6PmB6GTKIzoIvGct5KBGR6ae56T0ExJAXU9ss0hKxYo=,tag:cPGjqaLz+59q5Y5IBKdIjg==,type:str]
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:QFytjqDSOXWL3/ZbTeeosNKr3nSIsl3l/nOJa+/B,iv:IPBs5Glre1CzfE+tTkT252qKeD+Htfaq9Uc8gU5ji1s=,tag:tRNQLawj6j5LNaep9TteaA==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:2iMzPjCcQ+iwwBHGotho1ENlZRoyEUbJqPN5tIMw1kE=,iv:eiRdn5YVHqzjD/+qjfI4DNHikQTS+OKlI/lMUURavD4=,tag:rwkPgLlWoqmEAuuRtcGd4g==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:0V5kCe+KchkU+oGsdv75Tc8RM2I=,iv:PD02wem8Y4qmkMtkmwZASxXnVSygPM0TRwdTG2zPONE=,tag:I4wy6WNoRdgi3uf0/AsMqg==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:/22HjtE=,iv:QZgNS7hqHK8cqUuXcZ9KJRQpe5hqvrymYd6g5GFqDUU=,tag:sWuvH66A/7KLGs39vpKtTQ==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:CarfS0o6oKOelCExapbPdAw=,iv:T9h27I/zsztSnndy/+q7iJleZJOQB1HdEmboB1iEMlY=,tag:7Ld/x0rvbybuOaLdTUlC2A==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:3Yx5YIgAJPVbMwajKX8HtiBp6kqNqAGa/awDUd/XZjLgbeS0J7s7rbHMNRLGcI/OkcMStj2P+Q==,iv:NDSgB7Sn2gXUU2zxZSCp5VIBcygrIOU+IvqzQUMdDss=,tag:AVAoAFGxx+EtNH5pvE3Icw==,type:str]
    LLDAP_POSTGRES_USER: ENC[AES256_GCM,data:Hyu4wORqGw==,iv:4cu4NWXCzl4UyKPKdR3Pt6U4bsePlkxzBiVMjqrQ160=,tag:0/MYJ5UQTSB+H6rAuMspmg==,type:str]
    LLDAP_POSTGRES_PASS: ENC[AES256_GCM,data:Gn8xOWRqpTBZHjBKbXKc9xqLjsRSMh1Sbkw2GKG+OMun/RDZbP6KuRfpAQNZh+pdopNnubURO2pSHgmzds9g6g==,iv:GjzzJugpqoX6kOISnJMVchEef5A+phBZKQNTV0DLRhc=,tag:HnzfTXwr46k7IpcqbRr6uQ==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:f+i64bT+m5IAHyjybVoWOJKlLko9i0O92aspk4fUGEb8Jifu/wyDdq/baPgNOidRq/Vf9C3KTMe0Se87yNTzoQ==,iv:BmDZ/WpodHt2SzsEYV1S21RaXht+scHdUg0e/ECEy+M=,tag:IjwUH+RPu5zzDKMnB6P7eA==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:VBZ/x734eeW0jAOcWWpOF+zPIIhCOihGvlvgfx2NNBi5snSQcihq/zjbZD6nsR0T9H9A1d99sJfLdO6ER7PNpQ==,iv:ES5AR5dtuNZcpbUgUC8VG4TENogsVIzZT2suQej9sQo=,tag:ef3CgSwj2bbjw0IsuJgT7g==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:kWldlF2rjFwfOcrgKwwGUeNSSQZBZp5WsQMwpg6QyuHz6Fh6/GG+d+oGjIZZ+PvEYH9PoUiVGqaacGzQJCwx8A==,iv:o8jbVDnJFucuxOx8AO4junDwvF3n0wD31VL0zAndqfI=,tag:825zCzmY4pW6RGN7gGSrRw==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:sT+t9k4j+YsNPEbQniU+OsPXsvxhXiz0KSW9hQqiJB/tsU/LX8iplTnXv/6Jj7/4SNw4mfB2fxBc7lso8nQ/EA==,iv:8yRf2wyDZDS/ucio7wF5ADCIu+niyFbXgAIzr5mHKhc=,tag:cHAoQo/s+1tvQds9Uovp0Q==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:KUO7I0ixpRfRUw==,iv:2RgBylp10h8MhqWi71wBV7cFoYafCzNkDP7pxHHWZ/4=,tag:9+OvNb4Vu71BUtG2xLWxog==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:I+mxAa+mp3dF+s73NYsC+SMLx4AS/6buWSDAsz+EK108ZpOEkyic40fzQdcXQVrJR5UdvD+D4a9YVbWqOLqjCg==,iv:+nH2ps8jsbiTjnUx2jUMOiLgmEzshpl372+VtnURtDg=,tag:x2qifC0qRGrLYDrkvIeSTQ==,type:str]
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:3r7i1I/upWPRGEL6X71NFA==,iv:aBRaudVZk6PDqvJJ8V+vM436eht9si5alapnAZqbwN8=,tag:uUzr+3r4TaNaZGIPnw/Y+w==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:TtFgZOUv89NWxhNnouRWo5JmD/9i,iv:LW89G46d05hkgnmkAlAoSM2P8wxfkiF5qLFy3lWJSaE=,tag:Ut3NbMPEuTRVUqIm6xUZFQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:kTXqeTxutGiRgvLytQpX33VBNZA=,iv:N4d7fuDX82o7RsxNQib6Yq3xTTAGfTsf1WKMwJ879Nw=,tag:P6/kXazoYmC2SjJD0qredA==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:xGzekLo8+RP/YKCH/HbUO4Nhl7qyCMFUICohMqXZN1Z6F28j,iv:krjA6mLotbh0a7dYGXyg/d62NNBvoLPUSnqYnK5wHIU=,tag:iMyNBq/iyhFhco+ppbuuOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjN2oyL1lHbWp0UXFmcDB6
            UGtMbkxWODA2WitRS2NibnVuYkxTc3B5Z0RVCmJxeTUra0JDMm4yL1E0LzVjSHZa
            MWtZMW5hMjV2VzNJNTRvUXNYQ01OOWMKLS0tIDF5ejRRaWw5UWRPVGxjaC83NjVK
            QmxYU2FYZ0N2Z29lMTdhZnQyNU9jSUEKyG1YlQGZAqOI2namyYVUzFoW+7O9s5CL
            x/cy3nNdaILNiZtBPL9Zq6qvJSvQ0l+DCiGwEjBosA35m27eVooacw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-10T10:19:59Z"
    mac: ENC[AES256_GCM,data:z1ns6BTOJXNJK4zG+T8xPMgXJ/aTp203INf38GORYJCCtb58mV0dJn4cfx/x/XU+vQ/mwd/AcdKxBSx8ItnxqecPNs5xjnMgizcESnkvQmYgh3yImr71JbkDAINGpg1w3xAghaY345RUskloJ7FTF66AWmxIWh11vgavhtWC46U=,iv:K6ob7gja33X//IAozEmzjASbAvgQ83GxZzP5TqtSGqg=,tag:HfxC1nlCrpVZrDSM8uao6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
