apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:lZA6WRypO1J6cChoxWK7ZYvV8kVHg+YpKlXkZ5cQ/4U1BQD6PdsCAiaVsdHshxghx1YAlaadhrPKawQsBZEt3GYWAHFOjS0VU7U+mduNiY6W9WN0UfgYhKoeYsM3tA==,iv:g6RDox9WD85lSif2Bc+rZ7LXaxStpox7Xs9ziuZceJM=,tag:sKoXmGTKNeCMAfy3wlSiLA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:hvpKWhri1YF6HxA=,iv:LS+XCLVMk5R2vZoMzQJZGIYJ3AYV9/UqKZJdTQa9tS0=,tag:ojDnq9nxw/sO7v+P+Idy/Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:11s9xqKw4mMdUMA0ZVZnLjY=,iv:K3eRz0pSwY9GKwdsVSIdW0P/5RJK4nAgqtn9+L5vJd8=,tag:39KH8JfKfzqT9qkqykowzw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/2B693b4zA9FLT+CYAKE3CJyO/qCN9jlg4FNQbZFPI+vf9wv,iv:ubLLPhqCe5CcX1yhkBhqOlxbuKm7YuUC5HieHBdyccY=,tag:Rc2lMMhXbd5WkwHfC8B22A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeWZRL2NTWDAranJRQjhC
            RHZ0cnF1ZkVnS0wrOVNnTE5tUVhoeUF0VmpzClJWaE82ZUFKVkh3dHorTHNscldN
            UWdKYnlMck5LZjVaQ1lqdkYwVmZTZTQKLS0tIElTbkpXb3pkODBtZnlTR3l4MnJ1
            NWFBVHhua3U0UVVMNmhOOFdkVnJMQjAKqQO80+s9HA8ya08y2ErB8ZXlYqLW2Le1
            88L54/ATCm789Y+nMkIrFTMJ8GtSo8CrZdpGOoEX5pxKQ7TXwih62A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T21:31:19Z"
    mac: ENC[AES256_GCM,data:JtxPk3MdaXbRwtwuMF/qEwZRShh8fAsBMkBldV6H4zpcBu3SfbWIx1wn7yjDiW4ip9AYU7qUPmt/K1r1TV7DKWSDeVMhgffZ6KW3c8RX6Ts68tnH6r5przf/vgAnXt27UYhIUmc5I8rAzfl8XxrF7oYvcCcUpx6jk4lqNEL2onI=,iv:T+TQbDRb/s8KctOPSbw+WPJ1XO8F1oUy4vPU7BHgEoU=,tag:Lm4c2UcFYcQQsa6OjjuDvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
