apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BPDFeKsSLw2Dz/E=,iv:9ojwCCR1irLZkGgZZl9SOMbDtkLX+Hw66SJP5PVoxts=,tag:x2KoAqG4yNNo7uyE0COvCA==,type:str]
    INTERNAL_SERVICE_DOMAIN: ENC[AES256_GCM,data:gsDCzJ+evBfiWkn0f6y6v84=,iv:uRiHn+Ux3Ky0/jb8tCjoDvghjAuI890qTpMN1gEqxvs=,tag:BtjVjq9ji93zy9/Z1oTl9A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:318ebuxf2OqEVMiVaXVMWBQ=,iv:Mb/UodbJsEReSiyvMXERvM+HPMxPvNorU188UFdNw0k=,tag:NU/xt/ZbnrONcb1W714Q2w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zzNCv/LjOw7sQTQHbr2LP1TwtLyIXpHwtco+HDDEj6b7elT/,iv:aN2HVpjkgYp0/Xy6dL1Qv7H+udFCkF5Tn84GC8slCSo=,tag:8SfObCci4a+1N5aRwjWVMA==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:pRg0zri1OZ+VZV1humTa6UHHsoYXk7ZzM82lIDvq7JfQcyEg+eHnIlFwSTTDtlVWcOv/ZZDaxYLoHyYG,iv:rIPiy1ZsAs55lBYfkIoMGTjTztPKHKq0Euw7b05l68w=,tag:ucwDP4s0/pnxSIQ5jvPUZw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:mgjufe7mZZ75OkSYNMoZcGvvkEw=,iv:5JGR5JXBRcOProVxNKoWPzynoL7OD3US0a7vy27GDCk=,tag:2FQImm2jpHbAl4s2IajtOQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:K6HrcpKfdOHLThv847IoUjNoG6A=,iv:5giRbwe+Q2z+Z5ec+O8sdEZS3iqVWhVPjNQOhuMx9Eo=,tag:WydUkmN4/hQYFgdN9/T7gA==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:MnZhTBuY4vkVT6TkcUnrc3ao2yE=,iv:E/6U5lDcyi/mkIKQ991+zVKFiSpTFBfy8re0l4/XD8Y=,tag:eQfApf21m6M9msSSqZVrnQ==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:iOBmvCjsj7DFHA==,iv:1biCjPeXN5RwxGrKKd66i/xqwtASBErsJLM/1IqALIs=,tag:N+G1drFGaX2pXDCUaRZIkg==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:lDsmNeJGzceLDw==,iv:8erR+f2nulFNvl46xtZe6mL2Lk/OvfOkjPjq6RDXuxY=,tag:XbD6ow0BrJSrASzp2gAObw==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:BRMPnuoPvgSijA==,iv:3NIv9c+Wg1VZgRTnarYiUfjja6YSG/wnczcVHF2UypI=,tag:VpG6yc2ju0d57UbN7BEvQw==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:9/lbh6Rnemw=,iv:4B+OeffhGZ2KIomOo/zFjfSLG67DACLs6hEkUBwDNOU=,tag:JSn572Q1bNNZ/EOu4RLBBA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:J6FeJRD84iIRVtp0/91ktcrVAQ==,iv:8rL2/cs6k8uV8r3vsGR5HQpPOIAkpM4bIOq2hMwH5RQ=,tag:Elaz0v9yTAZ/8K9PAuuHOg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:yw6AjW0EXtjd,iv:31lrASRIL7FPYfI6aEX/78UdptK4jxrDBM1NxCgzKck=,tag:2ase/ip6sTOo4qT9ZnRCyw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:7Q/BxHHBRliqSg==,iv:AlMR/cmRHlxsAWwPTbfDj0rB6TO8lXlhCAKMvhHf3CM=,tag:xRXY2L1eIluZV/Q2BypgmA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:/GKNQ296d8YqjU7VVAY1RrRVcq5ZBsT+JkIt/mX3,iv:jpl/0670Ib+9XJx0fjOIqZFL91CKXeg8/JTajEZNht0=,tag:h5sms0Jw2WBA2BRhd4z50Q==,type:str]
    GATUS_PUSHOVER_TOKEN: ENC[AES256_GCM,data:fS6KBB3j5IZcbj+nnZneXXGMWfRRbtagzjWO6IYV,iv:T1XLyYdU32tM8G+OUGgJB3kL2REWcjvAMjgvk/2suq4=,tag:2GVVKpo4u1j9sSO2GRCy1Q==,type:str]
    SONARR_PUSHOVER_TOKEN: ENC[AES256_GCM,data:3nHu4JSgF3CgHXCoWjp2RVtUk7T1GdJCrMphfqBp,iv:a3zEUwZwHx3utVEEp/MPEy4EBE+UEchijmSu/Yw3Inc=,tag:/Y5R92NtNWbtsHC3gKmvpw==,type:str]
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:QFytjqDSOXWL3/ZbTeeosNKr3nSIsl3l/nOJa+/B,iv:IPBs5Glre1CzfE+tTkT252qKeD+Htfaq9Uc8gU5ji1s=,tag:tRNQLawj6j5LNaep9TteaA==,type:str]
    RADARR_PUSHOVER_TOKEN: ENC[AES256_GCM,data:FSi7d9wA79qU/5yJciwg4OBK4/Ao9Lu8UwFbUBV3,iv:1H/Q7wldS8ZuA8VbDnC0y6Yb4LnAKXfQVU3AKUogM/4=,tag:kSvlvorY3U0h3VaGfI9cpg==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:USKIMaJ+Uy9oMVWkuOeKcdTKEHBTbgjl7rFthpWO8ndBp989bb61p9xvu+4azw9TpdjXC//tyzdbUTwX3FA0Vg==,iv:6PmB6GTKIzoIvGct5KBGR6ae56T0ExJAXU9ss0hKxYo=,tag:cPGjqaLz+59q5Y5IBKdIjg==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:W/d9yay+/VEsfScc8sK41M2Keu2uy3z1H+mzaV3wlmrg2JsQASvT57nsnPZZdFR+R6QBT3PuiZSqCkfBY3zMOA==,iv:pWl78ryaLvfFI4TQs8j8dT38SPTz1Y9z8TKPV1OHdoQ=,tag:F4LTnXBGLmIe20ipAAM9qA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_USERNAME: ENC[AES256_GCM,data:j2TnB2FYotpckms=,iv:tvKe92x6BsXAJJXopAb0jihmjBhQb0Yk+IM9ZAcn22g=,tag:PPzvH189Da8r9Wn9Ki7imQ==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:29slhtTjQWM9vrnZYkJ2gl8U+PzCGVfRBZixw4g0tdCyrgxPaECBPpDGZCpCP1A91535AAuUHg5lQK/tGYlnww==,iv:hPXeFjdgzgqAkRaVnLl4W7wxDK5j+FAPaHl1wpF6aXw=,tag:U1tLNNYdolTbOOkKnS7Qbw==,type:str]
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:3r7i1I/upWPRGEL6X71NFA==,iv:aBRaudVZk6PDqvJJ8V+vM436eht9si5alapnAZqbwN8=,tag:uUzr+3r4TaNaZGIPnw/Y+w==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:TtFgZOUv89NWxhNnouRWo5JmD/9i,iv:LW89G46d05hkgnmkAlAoSM2P8wxfkiF5qLFy3lWJSaE=,tag:Ut3NbMPEuTRVUqIm6xUZFQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:kTXqeTxutGiRgvLytQpX33VBNZA=,iv:N4d7fuDX82o7RsxNQib6Yq3xTTAGfTsf1WKMwJ879Nw=,tag:P6/kXazoYmC2SjJD0qredA==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:xGzekLo8+RP/YKCH/HbUO4Nhl7qyCMFUICohMqXZN1Z6F28j,iv:krjA6mLotbh0a7dYGXyg/d62NNBvoLPUSnqYnK5wHIU=,tag:iMyNBq/iyhFhco+ppbuuOA==,type:str]
    MOSQUITTO_MQTT_USERNAME: ENC[AES256_GCM,data:ZjLYGtn8nZ4=,iv:rakFZM0SDdVSGeCKwrMk+XTJn0Tm2fy58Ce/MuJwmzY=,tag:CCYk4S9A0xFviDHbrgLnQw==,type:str]
    MOSQUITTO_MQTT_PASSWORD: ENC[AES256_GCM,data:90pu/ZiV9CfcMA==,iv:Xutd2jzZBHWuRE9U8Fh1vOhaQv3ZE/4VgYg4R8NTFUA=,tag:mMqbF0/DoKNMsbKlQ/wdKQ==,type:str]
    ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:DEpNeAvsBa0KMA==,iv:h9Bw9cBAv/sVfKjWrXf0tZcBPtZTAajI41YRBtRXac8=,tag:dypXvKPHdeNtfkFtra7zSQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:C3WUuAAv3rn4F79VLX7i9tE9L9cGKjX+gqwfZYKpfkmdjb08oHNPTw==,iv:FBKCEK46VEgD9YNLITnE0kmjAyN9NMH9by7M8lLyR9M=,tag:o7ti0Vaz30CsaLggI9n7rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjN2oyL1lHbWp0UXFmcDB6
            UGtMbkxWODA2WitRS2NibnVuYkxTc3B5Z0RVCmJxeTUra0JDMm4yL1E0LzVjSHZa
            MWtZMW5hMjV2VzNJNTRvUXNYQ01OOWMKLS0tIDF5ejRRaWw5UWRPVGxjaC83NjVK
            QmxYU2FYZ0N2Z29lMTdhZnQyNU9jSUEKyG1YlQGZAqOI2namyYVUzFoW+7O9s5CL
            x/cy3nNdaILNiZtBPL9Zq6qvJSvQ0l+DCiGwEjBosA35m27eVooacw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-11T21:58:58Z"
    mac: ENC[AES256_GCM,data:7FDY6xMTGfhOzoSBTNxYtA1Wpr8wrpg9REBkM50TgwM6tNcGIo40m7aNnhB0p5pQUY7aBof+rKuXoqHxJOe987XuL6x7kb30luZ/J3/j8mEbFElEiQ5x+IU+Eu5QcZAqPUahtEEcxzwA/XXaerNaL6I/P+oTlm3ODMbKhzBa7Ow=,iv:Tv5KAGCggBbamKij9NyetJeSeCwOBU85OU9VOiPRoRg=,tag:qKsVaur6QCYKsXBDPSOB1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
