---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-microservices
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: immich-server
      namespace: media
  values:
    controllers:
      immich-microservices:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.121.0@sha256:851c02f28891f1854c5b5762ee8d2e254e2de528cfe3627b2fbcb37a7f108ff3
            env:
              TZ: ${TIMEZONE}
              IMMICH_WORKERS_EXCLUDE: api
            envFrom:
              - configMapRef:
                  name: immich-configmap
              - secretRef:
                  name: immich
            resources:
              requests:
                cpu: 15m
                memory: 443M
              limits:
                memory: 600M
                gpu.intel.com/i915: 1
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
    persistence:
      library:
        enabled: true
        existingClaim: immich-upload
        globalMounts:
          - path: /usr/src/app/upload