---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &app pgadmin
  namespace: database
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
    # snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 100Mi