---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: storage
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16.2@sha256:3436dfbbc2799332a01361e007e3b408d016cfc235261e1caccc65e6edadf516
        envFrom:
          - secretRef:
              name: harbor-secret