apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Tp1KPIg5P1fwQLqlXgkl+4pCcw5eFA==,iv:Z8JV/op7vOXKX40cFZJenUyMzEm/nR9nyeKR2CTjz/o=,tag:Q0ccdHop0NtDMCdvjmOmOw==,type:str]
    password: ENC[AES256_GCM,data:7UDQsqk12qaVJOLxBOJvaavxvB33Pw==,iv:BWUvQy1/XuPOmsCvf5y+GJ2RED+StrGH8xFSZiXKk4g=,tag:tbXmZ7Y9CYaNHLoCewS+9A==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:NTIAXXKI8+KKxgGq2Q6mZfiJ,iv:pKTWQQBLJifLkPe6QmJ6ohrQjABJMBca9a8HQh9LQjU=,tag:JyfYA71gILTBSS9RxeiFXg==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:wYp7tAJRvHo1Jo1Rw1OZ+Yu6BSx1mA==,iv:gyTdDwko2o03G+K2/8xABaGds9h5cf5t29+Ec+Ey0i0=,tag:2SOZeSyn26yOQlrkJs3ttw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RkZSL0YwUGpTV0xJUm9m
            Q2E4TkJJakRyUUplYzlmTWJMRys2ekJwSUJ3CnE0R2xyK2RncVhOYnRHa0FOc24v
            Zkt4dGRTVThXV3d4MmVWM2MzUjhKK2sKLS0tIHhiOUoxbXdrK0hrNGkvQWdZTVR1
            dE5mK2dBUXNEb3ExUlhVRkJta1F1TEEK9vxUNpUPSuuhSZPKT9elivyAqLKS8KqA
            +oDrwYwTKZGxJd3OLKGzftWdz68Lf+bJMBEFoVFwxkhoHl4oW/sw4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T09:50:52Z"
    mac: ENC[AES256_GCM,data:4+4PG95YB3E1RNHqmHkWfMJCq3XdbtcSx+tXUDOn9eemlXB6hn0nuGSt8UMOIIZexC0ofoHFzuaMqIsweB/JgldGstHohLDON5BSu76CWa7mmzqPGyW7k/Yyay3czaap7jglQC1u9eMytUihu6teZxZLG3zw73RzH175C9GMKwo=,iv:5gbLkekQL/Yaaph4uV41PaziDQ8YpKZ0BN0RAEBTCkg=,tag:k3tpeA+gHVbP+VJHSEZhDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
