apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
stringData:
    mqtt_user: ENC[AES256_GCM,data:Leoy95n9Cn+PLq4jIRCJPpTJwVXVhCV8ATM=,iv:y7kY4AXqiR+GBn+4X4nuTKn/vnwVhs7DX1Yv8AgCIvw=,tag:vtqlxQad0Xhf9KY/akdGjQ==,type:str]
    mqtt_password: ENC[AES256_GCM,data:0+uYbffkfEDAG3FNJ2vXw1ngNWYmLxCZZ9o=,iv:tuhg8yJRhGZXeTyO9TDszSFNuJ6aBvsHedyvsIHEPM0=,tag:FF3uGp29DSrhSkRHyK830Q==,type:str]
    zigbee_pan_id: ENC[AES256_GCM,data:yDBYy07HyNo=,iv:XGqREWbCmw/Z9i0gGVSf0I9LgnQOtkGDgCxTFZ4DFbw=,tag:CJ/x3ouN0RnLyWpV/5dmNw==,type:str]
    zigbee_ext_pan_id: ENC[AES256_GCM,data:FLvygvRrg64=,iv:YTXZC58sccehbwIWVarJMpmTHdF9Q282Qf4vgX05ft4=,tag:K9BEY0YRrA2yLm5FiwielQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqN0NpcllUeFdPUzZrWXJD
            Kyt1aVovb2hSQUJZSGVjckxnM1lUV1h0bkJJCm8wQmdUcnE5c2V2b3NQVk5WN2tL
            M2x0blB2bytSVitDWkJIbGlLRVU5OUEKLS0tIENjb2VTbmpFQ251Um5ZN0s2bUlL
            TTVIZGRpVWVHU1NPS3BpN1dVQ1JIK1EK3qgjz/3t6xXVPDsq1notISsWtnREHJVJ
            4XhoOUMp09DJV89myAOi/F3bNkO+Uid7V3IQooUL03Gk7BF97eFy1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T16:58:33Z"
    mac: ENC[AES256_GCM,data:aZp5EUbfeI/M801lRDWeyUyucmAzqQQ3QboOe9YcGNbF3PABkQP39rlg/AvJlAOpdiDXKwWls94Q8mfOq4NLl9OKccjzdByQm1VHmV6IJp2yWl4+JgiWBHWsxKmv087Uyv/d6ku8SDCMINew+TBhiqHU77Np3mpLZFtXkHWfMuQ=,iv:Pywg48GNoEzy7mgmB1hdxRNlXKA1BEeIC0UnSnJmzO8=,tag:ztzvlfwA9pyUYw6HUnVrwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
