---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whoogle
  namespace: flux-system
spec:
  path: ./kubernetes/apps/service/whoogle/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: whoogle
      namespace: service
  interval: 30m
  retryInterval: 1m
  timeout: 3m