---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      defaultFsType: ext4
      reclaimPolicy: Delete
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
      backupTarget: s3://longhorn@us-east-1/
      backupTargetCredentialSecret: minio-secret
      taintToleration:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoExecute
    pspEnable: false
    longhornManager:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
    longhornDriver:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
    longhornUI:
      replicas: 1
    ingress:
      enabled: true
      ingressClassName: internal
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      secureBackends: false
      path: /