apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: storage
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:y94MokNlpure,iv:cUOHRkeYOAw8wawAhe+73hhGhcqaf75Ss9UTub/AN/Q=,tag:iZBhhDrjbcaK5+epgt8C1g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LDiLzs3r1xH3ug==,iv:JLBSUEqRLOB4/Nsx3xU4U+lZ+Va7/aEXr2BPx53BouY=,tag:79XW7w9jb1t/n4Vos+Nd6Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:XlFOPsq216SU7I7ZG+FGPHD/6+CrGDgmhAZiVgM=,iv:MIjdGyxwgMs7qmWr/uNgTEabu+4LiTR3/45UGSqp1NI=,tag:5NZjZ4hJxKISprhQmzKr7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MzBSYi8vV0hLdmx4aEhQ
            djdqcUJRYzVQbytHNzczL2tCWkFnQnExZ1FzCktsbnNlMnh6cytZMHpDVVU4UXZJ
            eExWdms2WEE2NnAxcTErUmswR09wOUUKLS0tIGNhazVIWlpFL0tKY1ZsMlNXdW9H
            S015SVh1djlQcytVV3d4MUNadkF1SFEK1sx9j4D1CrXD68EgJ7ji/c1y+74Jc2JC
            nIN+wtITLElElC/hgQTSas8KGlbCaZCDmrq7pZXbnAj3UKUPqXjORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T21:36:57Z"
    mac: ENC[AES256_GCM,data:JwSlSheNh23x2s5iE5Anb6POVQD46LP5oKAsEBxPWyFxvUA8PPvdLYBFMpv+mtwxwQp2G+LDAW2ZkNYyQm+cJJnJp+Qif+pTWsmUcOhPINbgQN70SfoHrPkHUQmT1Bpi4rZWDHX7BW52NqkuDKR68SrYOopA6JNJHJC4WLgfQDo=,iv:OwcRp5vXEemRi4nYQQzE6+xdwnLxxfWKVXhs66a/Mpk=,tag:u0FSBYtLcQ641qLLrF8B2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
