apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
    namespace: storage
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TsuKz18and7O,iv:fMAOxP+ZbtdqIBuS9Xpre2p/7kjoGU5JWOcgFo2H/Hc=,tag:OCOJEvxnDMQQTY2t6mcMoA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bfeuR7jSgUXmQQ==,iv:oH1uI/yzWFNH/NOGH2CvOFnkQtCU8gwTqmxsGgkuVtg=,tag:sATWJfEQBKfVrBcv42lhsA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:1NfbsQaeuXlMLkp1FHY=,iv:FePcKkByRS01B+gC65bcyBf1QBfAPc8Je5mQMrAWlDg=,tag:Tjb/FrgYwxpacePr9ghxIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MzBSYi8vV0hLdmx4aEhQ
            djdqcUJRYzVQbytHNzczL2tCWkFnQnExZ1FzCktsbnNlMnh6cytZMHpDVVU4UXZJ
            eExWdms2WEE2NnAxcTErUmswR09wOUUKLS0tIGNhazVIWlpFL0tKY1ZsMlNXdW9H
            S015SVh1djlQcytVV3d4MUNadkF1SFEK1sx9j4D1CrXD68EgJ7ji/c1y+74Jc2JC
            nIN+wtITLElElC/hgQTSas8KGlbCaZCDmrq7pZXbnAj3UKUPqXjORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T19:59:15Z"
    mac: ENC[AES256_GCM,data:NwB59rNReUEp3y9Y2Xnhqv3265ytT+qFQorNyKADuelBnhEYXRE5qDRLvqHl6SGcVlb4xVZl+/CbTN+z2Ip9PheIPVQod+Y/F3ZQClAbdl4eOpUUr9CTDzlexFGzu3QFkg906KmE6XXnt8e0oPvyj4Hraz3OqifhdVVbwgqUGx4=,iv:KfHTBHYxXx2FqmyZVeHE5/Ha6XbnSJCZNDaWgc8gEBo=,tag:PSZnBlcSR9RPD8eqMyD7Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
