apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
    namespace: storage
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TsuKz18and7O,iv:fMAOxP+ZbtdqIBuS9Xpre2p/7kjoGU5JWOcgFo2H/Hc=,tag:OCOJEvxnDMQQTY2t6mcMoA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bfeuR7jSgUXmQQ==,iv:oH1uI/yzWFNH/NOGH2CvOFnkQtCU8gwTqmxsGgkuVtg=,tag:sATWJfEQBKfVrBcv42lhsA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Flyv47wt3qpwfRfCgPh6fKzHsFs+1POYKbyaOLe+tFmyWOWMsbM=,iv:YuMdlryod2glsXKE0A2rQ4A+59z53B87Csv7/b6r1iE=,tag:iFDMOnd5B0duoXdDdOcZTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MzBSYi8vV0hLdmx4aEhQ
            djdqcUJRYzVQbytHNzczL2tCWkFnQnExZ1FzCktsbnNlMnh6cytZMHpDVVU4UXZJ
            eExWdms2WEE2NnAxcTErUmswR09wOUUKLS0tIGNhazVIWlpFL0tKY1ZsMlNXdW9H
            S015SVh1djlQcytVV3d4MUNadkF1SFEK1sx9j4D1CrXD68EgJ7ji/c1y+74Jc2JC
            nIN+wtITLElElC/hgQTSas8KGlbCaZCDmrq7pZXbnAj3UKUPqXjORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T20:05:10Z"
    mac: ENC[AES256_GCM,data:eg3wP+oX2lysTxA0czpFyclRSWreTkNKKPgg5TsUu+/qpMs74NXOR3cfFJj0LCN7ttJTN7rivBihUhCknMbwQFGkRhWqfbmbom7pDHmwvo6SpCgWzQEm13yJo5Wl8ySXKkAVV35t8iOJ8CAPKzk7H5AtdeulEaMvktgT4aSgeyE=,iv:QQKipLLTVGyJCy5/sFMuu/incBzqwZJ7bXY7Tb/9c3E=,tag:ifJFvODyItajhQTHUDmBRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
