---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app whoogle
  namespace: service
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/benbusby/whoogle-search
              tag: 0.8.4
            env:
              # WHOOGLE_ALT_TW: nitter.${SECRET_DOMAIN}
              WHOOGLE_ALT_YT: yt.${SECRET_DOMAIN}
              WHOOGLE_ALT_IG: imginn.com
              WHOOGLE_ALT_RD: reddit.${SECRET_DOMAIN}
              # WHOOGLE_ALT_MD: scripe.rip
              WHOOGLE_ALT_TL: farside.link/lingva
              WHOOGLE_ALT_IMG: bibliogram.art
              # WHOOGLE_ALT_WIKI: wikiless.org
              WHOOGLE_CONFIG_ALTS: 1
              WHOOGLE_CONFIG_COUNTRY: RU
              WHOOGLE_CONFIG_LANGUAGE: RU
              WHOOGLE_CONFIG_SEARCH_LANGUAGE: RU
              # WHOOGLE_CONFIG_GET_ONLY: 1
              WHOOGLE_CONFIG_THEME: system
              WHOOGLE_CONFIG_URL: https://whoogle.${SECRET_DOMAIN}/
              WHOOGLE_CONFIG_ANON_VIEW: "true"
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 250Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gatus.io/enabled: "true"
          hajimari.io/icon: mdi:google
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host