---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 30m
  chart:
    spec:
      chart: multus
      version: 5.0.4
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 5
    timeout: 15m
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
    timeout: 15m
  rollback:
    recreate: true
    cleanupOnFail: true
    timeout: 15m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2-thick

    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.5.1

      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin

    resources:
      requests:
        cpu: 5m
        memory: 29M
      limits:
        memory: 500M

    hostPaths:
      netns: /var/run/netns