# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: invidious-secret
    namespace: default
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:k64c5t9Tuv09,iv:xWTporvtPxYqIMCHgwX5oL3waGinXMiA5haD7xNS3hQ=,tag:sEJf+LbDLJdpOC+OF5wmiA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:yqLEYNPCcZLIVOVrJPRHSSvXW5jfP1h+IAfXNKXy/oZwYzxWH23N2Q==,iv:KuNcmIyJOz/fFqNTgo4lWsdNz+k1bHXmjcNk3ovR0Y8=,tag:w5iWrb2MTlDAXvM7ZGKkZA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:IQ86wO5ngLCThjI=,iv:aDb3BaPrZBr4qNZIbxQ3mnmu+DbJ9izdfD+AuYDy4Vg=,tag:WJY+et9jGZ9XleY06e7xOQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:4POrS9WB+CMce7IBcg7KBPHpf9v2X2mg,iv:X8hzDiVf2pmFEctsQabJXMG38P0UME6w374zN64NPKk=,tag:0RGmhBfGnLvzX6HS6PCaDA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GWnmQFPp8BJzGk9Y8HiNgQ6PT0hl8Q==,iv:2YvQ88wbEYwWcyc0bKP+9MPHgCiKnq0TgjEkZ98wEg4=,tag:oYpAkEaWfyXQdN/nILFVzw==,type:str]
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:qwjla0F8/YGQilTAukVC3mMb2ol+Td5D0JFH8qQhFVwrH0cTx377bBKeRLlWkMkCw55kbPN6dCjcLtQSoe4DMmNsKAgnL1kKifs89FcVhzG/SzM/GWeH8GS7ZC8nvvjpIqw54hIHVW4i9m8wnFE66J+ln8FLreF5Yw3KYlmjFwStkmM476DsECYzoxqOIT828bNR5NXxSiCA3+MfseibJzI1FTnHs8pGjWwMybCwS0VJZ9blNUGYBFFe86WYnHrHuZxMVN0BEXUAxZMICcqmRNjHZKN5t6eLAO1lzCe+cf4PXzUX2PxooMsIYqweNMJEQg==,iv:tsxQNwft6cA72Qg5gyeTLLqhulLGX9NnLajSD2X/Hp4=,tag:IJycYQ/HlY1hWjPiBbvpcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcGZ4SURiSC9YTHMzL1Nu
            QmVpdkx4VEhqbXlTRmUxWi9ybllTcHJPdld3CkdqVUVrTWV6dkJhcll6ZGlpbUVy
            MHBoQUpuNDFENXNLWFRNS2ovcU00dEkKLS0tIE1WSU03aXVsKzE0NWZ4b1pYRGtG
            QVhjdEtmNkVIZnZ6NEt3UXdNNForK2cKoFN7Mk/Z8rXeXElRCr0K/8ubypeBzmHE
            I8UUTkokS3YYj45P7BU62sMfdS1Xc/owyOuLkC/UpAu1pMsH5ovAJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T21:56:32Z"
    mac: ENC[AES256_GCM,data:Lpj8GF1lI6eX5+9t+kABWDfRQye60bktALp40R1glXBZ8NU+VeC8Mp+9n+Mblhe7w0oJdaGPMdbKv8hs9hiUa/8/BBu8XnNn5Gz9CEAX+En18wTfmjyH8emb37rkaLKqySQVHJrhTrnQWXX9yu9It80dWnhfamfceXtUBJN07es=,iv:71ZZJ8zfWHFyZ6slwQ2Lr0c7Lv1F47mId0jiMa0rfdg=,tag:6Oic5fCpmsscPETDoFsfIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
