---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: generic-device-plugin
  namespace: flux-system
spec:
  targetNamespace: kube-system
  path: ./kubernetes/apps/kube-system/generic-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m