---
apiVersion: stunner.l7mp.io/v1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: service
spec:
  realm: stunner.l7mp.io
  # authRef:
  #   name: stunner-auth-secret
  #   namespace: stunner