apiVersion: v1
kind: Secret
metadata:
    name: stunner-auth-secret
    namespace: service
stringData:
    type: ENC[AES256_GCM,data:qy8qjG16,iv:nRQ1Ks6l8zsGWAb5P3zVTaWdVcyStFhotWsNltOV++k=,tag:IKcJAtsK9w/lDvOH1xqyzg==,type:str]
    username: ENC[AES256_GCM,data:7ZTyu00IfZR6,iv:HGQitElLnuDS2rpr+Ug4DTY2Z269CoGUi4T7/Dqargs=,tag:XmWNzQwEWPjtFv0WTJi7DQ==,type:str]
    password: ENC[AES256_GCM,data:29+oZ8xdsn0jCg==,iv:fC9RRWid2nkIdVIRg2mriM5VDhas2I9X8qeZA54GeMQ=,tag:fyMRLkoe1tqde00U4u9T7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dSs2UXJpWGc5V3l0eTUz
            R3NzUzhSOHNkdlhTcE9SSE9HcnRBNS9uK1FJCjkyQzFyYzIzMVZuSTM5eFVzd0M3
            WVJjSEUyQ3NBSjhqbEg1RXlVUzB3ZlUKLS0tIG82U2QzWXNtMlZzZzFZTlZreHdO
            L3NHelFKTllKN0huNHNmaE9COGVKN00KeRP7GRlzmVuY4UbaWChZi9nyH0YpPn7Z
            yTYqOQp+abQgI0bHPu+w/OfK1BJfng7W5O9Nezepp26f8tuan4yUhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T18:47:13Z"
    mac: ENC[AES256_GCM,data:L6TsKW84xEIhwZfWKroVX0YURLZigSrUUUdGPX7Bo3txzy8yGhX26/fVK/BYjLHTzPp+biFtD9L80jDPjvGPiKDSECNJbm3JjqF/TXReQnRaAYuJT5FXK4vjRW8eRu+8Ow/AKwyfta5JdKT1h5Uk1ZMcIMk4P6DVAbkhh+UMMFw=,iv:jnd0QZxlz0eLbEo21XxxkxmgREZLU//diGHlKZlXK+E=,tag:gqBXVCWpNu6Qi73bTeDhQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
