---
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: frigate-server
  namespace: service
spec:
  parentRefs:
    - name: frigate-udp-gateway
  rules:
    - backendRefs:
        - name: frigate
          namespace: home
---
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: headless
  namespace: service
spec:
  parentRefs:
    - name: headless-gateway
  rules:
    - backendRefs:
        - name: headless-gateway
          namespace: service