---
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: frigate-plane
  namespace: service
spec:
  parentRefs:
    - name: frigate-udp-gateway
    # - name: frigate-tcp-gateway
  rules:
    - backendRefs:
      - name: frigate
        namespace: home