---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ollama
  namespace: ai
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
    controllers:
      main:
        type: deployment
        updateStrategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.1.27
            env:
              TZ: Europe/Simferopol
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              OLLAMA_SKIP_CPU_GENERATE: 1
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
            resources:
              requests:
                cpu: 200m
                memory: 8Gi
              limits:
                memory: 16Gi
                nvidia.com/gpu: 1
              startup:
                enabled: false
      bot:
        type: deployment
        updateStrategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: n4z3m/dialoqbase
              tag: latest
            env:
              TZ: Europe/Simferopol
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: ollama-secret
                    key: PGSTRING
              DB_REDIS_URL: redis://redis.database.svc.cluster.local:6379
              DB_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: ollama-secret
                    key: DBSECRETKEY
              DB_SESSION_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: ollama-secret
                    key: DB_SECRET_KEY
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                memory: 4Gi
    service:
      main:
        ports:
          http:
            port: 11434
      bot:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "ai.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
          - host: &host2 "dia.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: bot
                  port: http
        tls:
          - hosts:
              - *host
              - *host2
            secretName: wildcard-cert-tls
    persistence:
      models:
        enabled: true
        existingClaim: pvc-ollama
        mountPath: /root/.ollama