---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-fast