---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-backend
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-storage
