apiVersion: v1
kind: Secret
metadata:
    name: ollama-secret
stringData:
    TG_BOT_TOKEN: ENC[AES256_GCM,data:jgsjhi405zGKSAiT6306byTpypOiqPk6+7UrD7gONc4vMFf5H+Wb4WCRLbR7,iv:jd4EhuZT6AP5lvbE+u9SYeymMU3Qk526Xc5QnfJYvds=,tag:dc8JVxY4d1froCg/2Dg2Lw==,type:str]
    TG_ADMIN_IDS: ENC[AES256_GCM,data:L3uFSYM1GXwN,iv:vTIKVy1zzaJegHDvMb7L6SPu8bsnnanzi8a0Ii3qSIo=,tag:IFR0+JtfXTwBbgJj7ZAB9w==,type:str]
    TG_USER_IDS: ENC[AES256_GCM,data:vJ4YyMP03B5X,iv:9MlkX9x10KhO//ZoTO/SCDG/Vc+XKevBqlCRasPS3E0=,tag:8hSoVg5sOVG5f+V5USGKmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzxy9s9prfhu2ceqrt9hexs3tl402d7j2haumxl0lpn2pfycle6sz5kefj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RW0wb2p3Y1k2dllib0x3
            SVRYa3BzMWkvbWdTUndwY0tWN2xMWEVPaG1FCmc0UWdOa0VNM1EyQ3ZJV1pjZnZV
            Y21UNDd4bVIwczNyaVVYREJncnBFZ1UKLS0tICtqSEEvUlBrcVFsMUpEMzQ3YWUv
            MGt5K21SRjNrNnZwTmJSUERHM2ZNczAKsXPIyeU1aT42NhZAmWwr2OWZLVMQKVVs
            jfs8BzPXoIayuNhxXb7DDNSGej8GiceCmScnnX/9qEhQjqznFj8gmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T20:50:00Z"
    mac: ENC[AES256_GCM,data:RuU1R4bdXjM+q6yNL4tvXoSIQaUGp3nq5jzyfGH8xWq7twvYYQEt8ylpfYQKw43Db24UzKjKrU09Fq+0MYFpAjhwLMwan/0I7e2EyvQWBl+rsbOrBS2YW6QoYU4L2FP+sc6A/c0o0gS11yqnDcoZf5jEpv0LO3VTsHwia3G+e6Y=,iv:MPjh1QFFOMTnnwVte6/jYnrtZYxoiVgkd/5R8h3b4ms=,tag:NJSnd09smMjXtzOFWZG3PQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
