---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./longhorn/ks.yaml
  - ./minio/ks.yaml
  - ./samba-operator/ks.yaml
  - ./samba-share/ks.yaml
  # - ./harbor/ks.yaml